<?php


global $uttale_db_version;
$uttale_db_version = '1.2';


function uttale_install() {

	global $wpdb;
	global $uttale_db_version;

	$table_name = $wpdb->prefix . 'custom_uttale_skrivemate';

	$charset_collate = $wpdb->get_charset_collate();

	$sql = "CREATE TABLE $table_name (
	`ID` int(11) NOT NULL,
  `kons_vok` varchar(11),
  `gruppe` varchar(50),
  `grafem` varchar(11),
  `regeltype` varchar(50),
  `forklaring` varchar(256),
  `ipa` varchar(50),
  `eksempel` varchar(50),
  `lant_fra` varchar(50),
  `eksempel_ipa_ostlandsk` varchar(50),
  `ordkommentar` varchar(256)
)  $charset_collate;";

	require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
	dbDelta( $sql );

	add_option( 'uttale_db_version', $uttale_db_version );
}

function uttale_install_data() {
	global $wpdb;

	$table_name = $wpdb->prefix . 'custom_uttale_skrivemate';

// The actual data to be installed

$sql = "REPLACE INTO `wp_custom_uttale_skrivemate` (`ID`, `kons_vok`, `gruppe`, `grafem`, `regeltype`, `forklaring`, `ipa`, `eksempel`, `lant_fra`, `eksempel_ipa_ostlandsk`, `ordkommentar`) VALUES
(1, 'kons', 'b, p', '<b>', 'regel', '', 'b', 'briller', '', '²bɾɪlːəɾ', ''),
(2, 'kons', 'b, p', '<b>', 'regel', '', 'b', 'bjørkebark', '', '²bjœɾːkʲəbɑɾːkʲʰ', ''),
(3, 'kons', 'b, p', '<b>', 'regel', '', 'b', 'kebab', '', '¹kʲʰeːbɑb', ''),
(4, 'kons', 'b, p', '<b>', 'regel', 'foran ustemt konsonant', 'p', 'absolutt', '', 'ɑpsɔ¹lʉtʰː', ''),
(5, 'kons', 'b, p', '<b>', 'regel', 'foran ustemt konsonant i trykksterk stavelse med kort vokal', 'pː', 'Ibsen', '', '¹ɪpːsn͏ͅ', ''),
(6, 'kons', 'b, p', '<b>', 'regel', 'foran ustemt konsonant i trykksterk stavelse med kort vokal', 'pː', 'substantiv', '', '²sʉpːstɑntʰiːʋ', ''),
(7, 'kons', 'b, p', '<bb>', 'regel', '', 'bː', 'ribbe', '', '²ɾɪbːə', ''),
(8, 'kons', 'b, p', '<p>', 'regel', '', 'p / pʰ', 'pip', '', '¹pʰiːpʰ', ''),
(9, 'kons', 'b, p', '<p>', 'regel', '', 'p / pʰ', 'spansk', '', '¹spɑnːskʲ', ''),
(10, 'kons', 'b, p', '<p>', 'regel', '', 'p / pʰ', 'operasjon', '', 'ɔpəɾɑ¹ʃuːn', ''),
(11, 'kons', 'b, p', '<p>', 'regel', 'etter kort vokal og foran konsonant i trykksterk stavelse', 'pː', 'paprika', '', '¹pʰɑpːɾɪkɑ', ''),
(12, 'kons', 'b, p', '<p>', 'regel', 'etter kort vokal og foran konsonant i trykksterk stavelse', 'pː', 'dypt', '', '¹dʏpʰːtʰ', ''),
(13, 'kons', 'b, p', '<p>', 'regel', 'etter kort vokal og foran konsonant i trykksterk stavelse', 'pː', 'raps', '', '¹ɾɑpːs', ''),
(14, 'kons', 'b, p', '<pp>', 'regel', '', 'pː', 'suppe', '', '²sʉpːə', ''),
(15, 'kons', 'b, p', '<pp>', 'regel', '', 'pː', 'lepper', '', '²lɛpːɘɾ', ''),
(16, 'kons', 'b, p', '<pp>', 'regel', 'i slutten av ord', 'pʰː ', 'slapp', '', '¹ʃlɑpʰː', ''),
(17, 'kons', 'd, t', '<d>', 'regel', '', 'd', 'dag', '', '¹dɑːgʲ', ''),
(18, 'kons', 'd, t', '<d>', 'regel', '', 'd', 'kjedelig', '', '²çeːdəlɪ', ''),
(19, 'kons', 'd, t', '<d>', 'regel', '', 'd', 'arbeid', '', '²ɑɾːbæ͜ɪd', ''),
(20, 'kons', 'd, t', '<d>', 'regel', 'foran konsonant', 'dː ', 'midlertidig', '', '²mɪdːləʈʰiːdɪ', ''),
(21, 'kons', 'd, t', '<d>', 'regel', 'foran konsonant', 'dː ', 'padle', '', '²pʰɑdːlə', ''),
(22, 'kons', 'd, t', '<d>', 'regel', 'foran konsonant', 'dː ', 'pudre', '', '²pʰʉdːɾə', ''),
(23, 'kons', 'd, t', '<d>', 'regel', 'foran konsonant', 'dː ', 'sladre', '', '²ʃlɑdːɾə', ''),
(24, 'kons', 'd, t', '<d>', 'regel', 'i slutten av ord etter vokal (inkludert bøyde former av ordene)', '–', 'glad', '', '¹glɑː', ''),
(25, 'kons', 'd, t', '<d>', 'regel', 'i slutten av ord etter vokal (inkludert bøyde former av ordene)', '–', 'glade', '', '²glɑːə', ''),
(26, 'kons', 'd, t', '<d>', 'regel', 'i slutten av ord etter vokal (inkludert bøyde former av ordene)', '–', 'ved', '', '¹veː', ''),
(27, 'kons', 'd, t', '<d>', 'regel', 'i slutten av ord etter vokal (inkludert bøyde former av ordene)', '–', 'veden', '', '¹veːən', ''),
(28, 'kons', 'd, t', '<d>', 'regel', 'i slutten av ord etter vokal (inkludert bøyde former av ordene)', '–', 'brød', '', '¹bɾøː', ''),
(29, 'kons', 'd, t', '<d>', 'regel', 'i slutten av ord etter vokal (inkludert bøyde former av ordene)', '–', 'brødet', '', '¹bɾøːə', ''),
(30, 'kons', 'd, t', '<d>', 'regel', 'i slutten av ord etter vokal (inkludert bøyde former av ordene)', '–', 'tida', '', '¹tʰiːɑ', ''),
(31, 'kons', 'd, t', '<d>', 'unntak', '', 'd', 'bad', '', '¹bɑːd', ''),
(32, 'kons', 'd, t', '<d>', 'unntak', '', 'd', 'gud', '', '¹gʲʉːd', ''),
(33, 'kons', 'd, t', '<d>', 'unntak', '', 'd', 'spyd', '', '¹spyːd', ''),
(34, 'kons', 'd, t', '<d>', 'regel', 'mellom kort vokal og <s>', 'tː', 'tilfreds', '', 'tɪl¹fɾɛtːs', ''),
(35, 'kons', 'd, t', '<d>', 'regel', 'mellom kort vokal og <s>', 'tː', 'arbeidsgiver', '', '²ɑɾːbæ͜ɪtsjiːʋɘɾ', ''),
(36, 'kons', 'd, t', '<d>', 'regel', 'mellom kort vokal og <s>', 'tː', 'deltidsjobb', '', '¹deːltɪtsjɔbː', ''),
(37, 'kons', 'd, t', '<d>', 'spesiell uttale', 'stum d', 'd', 'djup', '', '¹jʉːp', ''),
(38, 'kons', 'd, t', '<dd>', 'regel', '', 'dː', 'pudder', '', '¹pʰʉdːɘɾ', ''),
(39, 'kons', 'd, t', '<dd>', 'regel', '', 'dː', 'sladder', '', '¹ʃlɑːdɘɾ', ''),
(40, 'kons', 'd, t', '<dt>', 'regel', '', 't / tː', 'rundt', '', '¹ɾʉnːtʰ', ''),
(41, 'kons', 'd, t', '<dt>', 'regel', '', 't / tː', 'midten', '', '¹mɪtːnͅ', ''),
(42, 'kons', 'd, t', '<dt>', 'regel', '', 't / tː', 'henvendt', '', '¹hɛnːʋɛnːtʰ', ''),
(43, 'kons', 'd, t', '<dt>', 'regel', '', 't / tː', 'rødt', '', '¹ɾœtʰː', ''),
(44, 'kons', 'd, t', '<dt>', 'regel', '', 't / tː', 'bedt', '', '¹bɛtʰː', ''),
(45, 'kons', 'd, t', '<t>', 'regel', '', 't / tʰ', 'te', '', '¹tʰeː', ''),
(46, 'kons', 'd, t', '<t>', 'regel', '', 't / tʰ', 'latskap', '', '¹lɑːtskɑːpʰ', ''),
(47, 'kons', 'd, t', '<t>', 'regel', '', 't / tʰ', 'aristokrati', '', 'ɑɾɪstʊkʲɾɑ¹tʰiː', ''),
(48, 'kons', 'd, t', '<t>', 'regel', 'mellom kort vokal og konsonant i trykksterk stavelse', 'tː ', 'vits', '', '¹ʋɪtːs', ''),
(49, 'kons', 'd, t', '<t>', 'regel', 'mellom kort vokal og konsonant i trykksterk stavelse', 'tː ', 'erstatning', '', 'æ¹ʃʈɑtːnɪŋ', ''),
(50, 'kons', 'd, t', '<t>', 'regel', 'mellom kort vokal og konsonant i trykksterk stavelse', 'tː ', 'klatre', '', '¹kʲʰlɑtːɾə', ''),
(51, 'kons', 'd, t', '<t>', 'regel', 'i substantivendelsen bestemt form entall av substantiv i intetkjønn', '–', 'fjellet', '', '¹fjɛlːə', ''),
(52, 'kons', 'd, t', '<t>', 'regel', 'i substantivendelsen bestemt form entall av substantiv i intetkjønn', '–', 'badet', '', '¹bɑːdə', ''),
(53, 'kons', 'd, t', '<t>', 'regel', 'i substantivendelsen bestemt form entall av substantiv i intetkjønn', '–', 'beinet', '', '¹bæ͜ɪnə', ''),
(54, 'kons', 'd, t', '<t>', 'spesiell uttale', 't som d', 'd', 'i like måte ', '', 'ɪ²liːgʲə²moːdə', ''),
(55, 'kons', 'd, t', '<th>', 'fremmedord', '', 'tː / tʰ', 'luthersk', 'tysk', '¹lʉtːəʃkʲʰ', ''),
(56, 'kons', 'd, t', '<th>', 'fremmedord', '', 'tː / tʰ', 'thai', 'andre', '¹tʰɑ͜ɪ', ''),
(57, 'kons', 'd, t', '<tt>', 'regel', '', 'tː', 'glitter', '', '¹gʲlɪtːɘɾ', ''),
(58, 'kons', 'd, t', '<tt>', 'regel', 'i slutten av ord', ' tːʰ ', 'absolutt', '', 'ɑpsɔ¹lʉtʰː', ''),
(59, 'kons', 'f, v', '<f>', 'regel', '', 'f', 'film', '', '¹fɪlːm', ''),
(60, 'kons', 'f, v', '<f>', 'regel', '', 'f', 'professor', '', 'pʰɾʊ¹fɛsːʊɾ', ''),
(61, 'kons', 'f, v', '<f>', 'regel', '', 'f', 'sjef', '', '¹ʃeːf', ''),
(62, 'kons', 'f, v', '<f>', 'regel', 'etter kort vokal foran konsonant i trykksterk stavelse', 'fː ', 'aften', '', '²ɑfːtn͏ͅ', ''),
(63, 'kons', 'f, v', '<f>', 'regel', 'etter kort vokal foran konsonant i trykksterk stavelse', 'fː ', 'løfte', '', '²lœfːtə', ''),
(64, 'kons', 'f, v', '<f>', 'regel', 'etter kort vokal foran konsonant i trykksterk stavelse', 'fː ', 'trøfler', '', '¹tʰɾœf:lɘɾ', ''),
(65, 'kons', 'f, v', '<ff>', 'regel', '', 'fː', 'kaffe', '', '¹kʰɑfːə', ''),
(66, 'kons', 'f, v', '<v>', 'regel', '', 'ʋ', 'vin', '', '¹ʋiːn', ''),
(67, 'kons', 'f, v', '<v>', 'regel', '', 'ʋ', 'avgjøre', '', '¹ɑːʋjøːɾə', ''),
(68, 'kons', 'f, v', '<v>', 'regel', '', 'ʋ', 'rev', '', '¹ɾeːʋ', ''),
(69, 'kons', 'f, v', '<v>', 'unntak', 'stum <v> etter <lv> sist i noen ord (men uttales i elv, gulv, kalv, selve m.fl.)', '–', 'sølv', '', '¹sœlː', ''),
(70, 'kons', 'f, v', '<v>', 'unntak', 'stum <v> etter <lv> sist i noen ord (men uttales i elv, gulv, kalv, selve m.fl.)', '–', 'halv', '', '¹hɑɫː', ''),
(71, 'kons', 'f, v', '<v>', 'unntak', 'stum <v> etter <lv> sist i noen ord (men uttales i elv, gulv, kalv, selve m.fl.)', '–', 'selv', '', '¹sɛlː ', ''),
(72, 'kons', 'f, v', '<v>', 'unntak', 'stum <v> etter <lv> sist i noen ord (men uttales i elv, gulv, kalv, selve m.fl.)', '–', 'tolv', '', '¹tʰɔɫː', ''),
(73, 'kons', 'f, v', '<v>', 'regel', 'mellom kort vokal og konsonant i trykksterk stavelse, og noen enkeltord', 'ʋː', 'levde', '', '²lɛʋːdə', ''),
(74, 'kons', 'f, v', '<v>', 'regel', 'mellom kort vokal og konsonant i trykksterk stavelse, og noen enkeltord', 'ʋː', 'tavle', '', '²tʰɑʋːlə', ''),
(75, 'kons', 'f, v', '<v>', 'regel', 'mellom kort vokal og konsonant i trykksterk stavelse, og noen enkeltord', 'ʋː', 'støvel', '', '²stœʋːəl', ''),
(76, 'kons', 'f, v', '<v>', 'regel', 'mellom kort vokal og konsonant i trykksterk stavelse, og noen enkeltord', 'ʋː', 'høvel', '', '¹hœʋːɘl', ''),
(77, 'kons', 'f, v', '<v>', 'regel', 'foran <s> og <t> i samme stavelse', 'f', 'grovt', '', '¹gʲɾoːft', ''),
(78, 'kons', 'f, v', '<v>', 'regel', 'foran <s> og <t> i samme stavelse', 'f', 'alternativt', '', 'ɑɫ¹tʰæɳːɑtʰiːftʰ', ''),
(79, 'kons', 'f, v', '<v>', 'regel', 'foran <s> og <t> i samme stavelse', 'f', 'livsfare', '', '¹lɪfːsfɑːɾə', ''),
(80, 'kons', 'f, v', '<hv>', 'regel', '', 'ʋ', 'hvorfor', '', '¹ʋʊɾːfʊɾ', ''),
(81, 'kons', 'f, v', '<hv>', 'regel', '', 'ʋ', 'hvete', '', '²ʋeːtə', ''),
(82, 'kons', 'f, v', '<w>', 'regel', '', 'ʋ', 'Wenche', '', '²ʋɛŋːkʲə', ''),
(83, 'kons', 'f, v', '<w>', 'fremmedord', '', 'ʋː', 'show ', 'engelsk', '¹ʃɔʋː', 'alternativ uttale med ɔ͜͜ʊ'),
(84, 'kons', 'f, v', '<w>', 'fremmedord', '', '-', 'cowboy', 'engelsk', '¹kʰɔbːɔ͜ɪ', ''),
(85, 'kons', 'f, v', '<w>', 'fremmedord', '', '-', 'rickshaw', 'engelsk', '¹ɾɪkʲːʃɔ', ''),
(86, 'kons', 'f, v', '<wh>', 'fremmedord', '', 'ʋ', 'whisky', '', '¹ʋɪsːkʲɪ', ''),
(87, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran a- og å-lyd ', 'g', 'gal', '', '¹gɑːɫ', ''),
(88, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran a- og å-lyd ', 'g', 'foregå', '', '²foːɾəgoː', ''),
(89, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran a- og å-lyd ', 'g', 'obligatorisk', '', 'ɔblɪgɑ¹tʰuːɾɪskʲ', ''),
(90, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'gem', '', '¹gʲeːm', ''),
(91, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'gen', '', '¹gʲeːn', ''),
(92, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'gebiss', '', 'gʲɛ¹bɪsː', ''),
(93, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'gebyr', '', 'gʲɛ¹byːɾ', ''),
(94, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'genser', '', '¹gʲɛnːsɘɾ', ''),
(95, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'general', '', 'gʲɛnə¹ɾɑːl', ''),
(96, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'genial', '', 'gʲɛnɪ¹ɑːl', ''),
(97, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'geografi', '', 'gʲɛʊgʲɾɑ¹fiː', ''),
(98, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'gratis', '', '¹gʲɾɑːtɪs', ''),
(99, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran e, r og i slutten av ord', 'gʲ', 'hverdag', '', '²ʋæːɖɑːɡʲ', ''),
(100, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran konsonant', 'gʲː', 'lagde', '', '²lɑgʲːdə', ''),
(101, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran konsonant', 'gʲː', 'sagd', '', '¹sɑgʲːd', ''),
(102, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran konsonant', 'gʲː', 'Agder', '', '¹ɑgʲːdɘɾ', ''),
(103, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran konsonant', 'gʲː', 'megler', '', '²mɛgʲːlɘɾ', ''),
(104, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran konsonant', 'gʲː', 'regle', '', '²ɾɛgʲːlə', ''),
(105, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran konsonant', 'gʲː', 'logre', '', '²lɔgʲːɾə', ''),
(106, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran s', 'kʲ(ː)', 'dagstur', '', '¹dɑkʲːstʰʉːɾ', ''),
(107, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran s', 'kʲ(ː)', 'lørdagsgodt', '', '²løːɖɑkʲsgʲɔtʰː', ''),
(108, 'kons', 'g, k, j, ç', '<g>', 'regel', 'etter kort vokal foran s', 'kʲ(ː)', 'roligst', '', '¹ɾuːlɪkʲstʰ', ''),
(109, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gift', '', '¹jɪfːt', ''),
(110, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'giver', '', '²jiːʋɘɾ', ''),
(111, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gjedde', '', '²jɛdːə', ''),
(112, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'avgjøre', '', '¹ɑːʋjøːɾə', ''),
(113, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gjorde', '', '²juːɾə', ''),
(114, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gyldig', '', '²jʏlːdɪ', ''),
(115, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gylf', '', '¹jʏlːf', ''),
(116, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gyllen', '', '²jʏlːn͏ͅ', ''),
(117, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gyte', '', '²jyːtə', ''),
(118, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gys', '', '¹jʏːs', ''),
(119, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'gyve', '', '²jyːʋə', ''),
(120, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'geipe', '', '²jæ͜ɪpə', ''),
(121, 'kons', 'g, k, j, ç', '<g>', 'regel', 'foran i, y og ei', 'j', 'geit', '', '¹jæ͜ɪtʰ', ''),
(122, 'kons', 'g, k, j, ç', '<g>', 'unntak', '', 'gʲ', 'Geir', '', '¹gʲæ͜ɪɾ', ''),
(123, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'gire', 'engelsk', '²gʲiːɾə', ''),
(124, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'gitar', 'spansk', 'gʲɪ¹tɑːɾ', ''),
(125, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'terminologi', 'gresk', 'tʰæɾmɪnʊlʊ¹gʲiː', ''),
(126, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'gitar', '', 'gʲɪ¹tɑːɾ', ''),
(127, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'gymnas', 'latin', 'gʲʏm¹nɑːs', ''),
(128, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'gym', 'latin', '¹gʲʏmː', ''),
(129, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'gynekolog', 'gresk', 'gʲʏnəkʊ¹loːgʲ', ''),
(130, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'geisha', 'japansk', '¹gʲæ͜ɪʃɑ', ''),
(131, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'begeistret', 'tysk', 'bɛ¹gʲæ͜ɪstɾətʰ', ''),
(132, 'kons', 'g, k, j, ç', '<g>', 'fremmedord', '', 'gʲ', 'geistlig', 'tysk', '²gʲæ͜ɪstlɪ', ''),
(133, 'kons', 'g, k, j, ç', '<g>', 'regel', 'i slutten av ord med endelsen -ig (inkludert bøyde former av ordene)', '-', 'farlig', '', '²fɑːlɪ', ''),
(134, 'kons', 'g, k, j, ç', '<g>', 'regel', 'i slutten av ord med endelsen -ig (inkludert bøyde former av ordene)', '-', 'viktig', '', '²ʋɪkʲːtɪ', ''),
(135, 'kons', 'g, k, j, ç', '<g>', 'regel', 'i slutten av ord med endelsen -ig (inkludert bøyde former av ordene)', '-', 'farlige', '', '²fɑːlɪə', ''),
(136, 'kons', 'g, k, j, ç', '<g>', 'regel', 'i slutten av ord med endelsen -ig (inkludert bøyde former av ordene)', '-', 'viktige', '', '²ʋɪkʲːtɪə', ''),
(137, 'kons', 'g, k, j, ç', '<g>', 'regel', 'i slutten av ord med som slutter med -eig (inkludert bøyde former av ordene)', '-', 'deig', '', '¹dæ͜ɪ', ''),
(138, 'kons', 'g, k, j, ç', '<g>', 'regel', 'i slutten av ord med som slutter med -eig (inkludert bøyde former av ordene)', '-', 'kjøttdeig', '', '²çœtːæ͜ɪ', ''),
(139, 'kons', 'g, k, j, ç', '<g>', 'regel', 'i slutten av ord med som slutter med -eig (inkludert bøyde former av ordene)', '-', 'seig', '', '¹sæ͜ɪ', ''),
(140, 'kons', 'g, k, j, ç', '<g>', 'unntak', '', 'gʲ', 'feig', '', '¹fæ͜ɪgʲ', ''),
(141, 'kons', 'g, k, j, ç', '<g>', 'unntak', '', 'gʲ', 'teig', '', '¹tʰæ͜ɪgʲ', ''),
(142, 'kons', 'g, k, j, ç', '<g>', 'unntak', '', 'gʲ', 'treig', '', '¹tʰɾæ͜ɪgʲ', ''),
(143, 'kons', 'g, k, j, ç', '<g>', 'spesiell uttale', '', '-', 'og                ', '', '¹ɔ', ''),
(144, 'kons', 'g, k, j, ç', '<g>', 'spesiell uttale', '', '-', 'også             ', '', '¹ɔsːɔ', ''),
(145, 'kons', 'g, k, j, ç', '<g>', 'spesiell uttale', '', '-', 'fugl', '', '¹fʉːl', ''),
(146, 'kons', 'g, k, j, ç', '<gg>', 'regel', 'foran a- og å-lyd', 'gː', 'hoggorm', '', '¹hɔgːɔɾm', ''),
(147, 'kons', 'g, k, j, ç', '<gg>', 'regel', 'foran a- og å-lyd', 'gː', 'vogga', '', '²ʋɔgːɑ', ''),
(148, 'kons', 'g, k, j, ç', '<gg>', 'regel', 'foran e og i og i slutten av ord', 'gʲː', 'ligge', '', '²lɪgʲːə', ''),
(149, 'kons', 'g, k, j, ç', '<gg>', 'regel', 'foran e og i og i slutten av ord', 'gʲː', 'anlegg', '', '²ɑnːlɛgʲː', ''),
(150, 'kons', 'g, k, j, ç', '<gg>', 'regel', 'foran e og i og i slutten av ord', 'gʲː', 'begge', '', '²bɛgʲːə', ''),
(151, 'kons', 'g, k, j, ç', '<gj>', 'regel', '', 'j', 'gjedde', '', '²jɛdːə', ''),
(152, 'kons', 'g, k, j, ç', '<gj>', 'regel', '', 'j', 'avgjøre', '', '¹ɑːʋjøːɾə', ''),
(153, 'kons', 'g, k, j, ç', '<gj>', 'regel', '', 'j', 'gjorde', '', '²juːɾə', ''),
(154, 'kons', 'g, k, j, ç', '<k>', 'regel', 'etter s foran a-, o- og å-lyd og av og til i trykksvake stavelser foran a-, o- og å-lyd', 'k', 'utroskap', '', '²ʉːtɾʊskɑːpʰ', ''),
(155, 'kons', 'g, k, j, ç', '<k>', 'regel', 'etter s foran a-, o- og å-lyd og av og til i trykksvake stavelser foran a-, o- og å-lyd', 'k', 'biskop', '', '²bɪsːkɔpʰ', ''),
(156, 'kons', 'g, k, j, ç', '<k>', 'regel', 'etter s foran a-, o- og å-lyd og av og til i trykksvake stavelser foran a-, o- og å-lyd', 'k', 'gynekolog', '', 'gʲʏnəkʊ¹loːgʲ', ''),
(157, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I begynnelsen av trykksterke stavelser foran a, o- og å-lyd', 'kʰ ', 'kamp', '', '¹kʰɑmːp', ''),
(158, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I begynnelsen av trykksterke stavelser foran a, o- og å-lyd', 'kʰ ', 'amerikansk', '', 'ɑmɛɾɪ¹kʰɑːnskʲʰ', ''),
(159, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I begynnelsen av trykksterke stavelser foran a, o- og å-lyd', 'kʰ ', 'kokos', '', '¹kʰʊkːʊs', ''),
(160, 'kons', 'g, k, j, ç', '<k>', 'regel', 'i trykksvake stavelser', 'kʲ ', 'vanske', '', '²ʋɑnːskʲə', ''),
(161, 'kons', 'g, k, j, ç', '<k>', 'regel', 'i trykksvake stavelser', 'kʲ ', 'laken', '', '¹lɑːkʲɘn', ''),
(162, 'kons', 'g, k, j, ç', '<k>', 'regel', 'i trykksvake stavelser', 'kʲ ', 'leketøy', '', '²leːkʲətʰœ͜ʏ', ''),
(163, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I trykksterke stavelser foran konsonant', 'kʲ:', 'jukse', '', '²jʊkʲːsə', ''),
(164, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I trykksterke stavelser foran konsonant', 'kʲ:', 'lekse', '', '²lɛkʲːsə', ''),
(165, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I trykksterke stavelser foran konsonant', 'kʲ:', 'lykt', '', '¹lʏkʲ:tʰ', ''),
(166, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I begynnelsen av trykksterke stavelser og i slutten av ord', 'kʲʰ', 'klaver', '', 'kʲʰlɑ¹veːɾ', ''),
(167, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I begynnelsen av trykksterke stavelser og i slutten av ord', 'kʲʰ', 'apotek', '', 'ɑpʊ¹tʰeːkʲʰ', ''),
(168, 'kons', 'g, k, j, ç', '<k>', 'regel', 'I begynnelsen av trykksterke stavelser og i slutten av ord', 'kʲʰ', 'indisk', '', '¹ɪnːdɪskʲʰ', ''),
(169, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'kirke', '', '²çɪɾːkʲə', ''),
(170, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'kikkert', '', '¹çɪkʲːəʈ', ''),
(171, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'kilde', '', '²çɪlːdə', ''),
(172, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'kilo', '', '¹çiːlʊ', ''),
(173, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'kyss ', '', '¹çʏsː', ''),
(174, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'kylling', '', '²çʏlːɪŋ', ''),
(175, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'kynisk', '', '¹çyːnɪskʲʰː', ''),
(176, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'keivhendt', '', '²çæ͜ɪʋhɛnt', ''),
(177, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran i, y og ei', 'ç', 'keitete', '', '²çæ͜ɪtːətə', ''),
(178, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'kidnappe', 'engelsk', '¹kʲɪdːnapːə', ''),
(179, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'kick', 'engelsk', '¹kʲɪːkʲʰː', ''),
(180, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'kimono', 'japansk', '¹kʲɪmːʊnʊ', ''),
(181, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'kyrillisk', 'andre', 'kʲʰʏ¹ɪlːɪskʲʰ', ''),
(182, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'kyrie', 'andre', '¹kʲyːɾɪə', ''),
(183, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'kypriotisk', 'andre', 'kʲʰʏpɾɪ¹uːtʰɪskʲʰ', ''),
(184, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'keitering', 'engelsk', '¹kʲʰɛ͜ɪtɛɾɪŋ', ''),
(185, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', '', 'kʲ', 'keiser', 'latin', '²kʲʰæ͜ɪsəɾ', ''),
(186, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', 'i ordet keramikk og dets avledninger', 'ç', 'keramikk', '', 'çæɾɑ¹mɪkʲʰː', ''),
(187, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', 'i ordet keramikk og dets avledninger', 'ç', 'keramiker', '', 'çæ¹ɾɑːmɪkʲɘɾ', ''),
(188, 'kons', 'g, k, j, ç', '<k>', 'fremmedord', 'i ordet keramikk og dets avledninger', 'ç', 'keramisk', '', 'çæ¹ɾɑːmɪskʲʰ', ''),
(189, 'kons', 'g, k, j, ç', '<k>', 'regel', 'foran n i lånord fra engelsk', '-', 'knockout', 'engelsk', '¹nɔkʲːɑ͜ʊtʰ', ''),
(190, 'kons', 'g, k, j, ç', '<k>', 'spesiell uttale', '', 'gʲ', 'i like måte ', '', 'ɪ²liːgʲə²moːdə', ''),
(191, 'kons', 'g, k, j, ç', '<kk>', 'regel', '', 'kʲ:', 'jakke', '', '²jɑkʲ:ə', ''),
(192, 'kons', 'g, k, j, ç', '<kk>', 'regel', '', 'kʲ:', 'lykken', '', '²lʏkʲːɘn', ''),
(193, 'kons', 'g, k, j, ç', '<kk>', 'regel', 'foran a-, o- og å-lyd ', 'k: ', 'ekko', '', '¹ɛkːʊ', ''),
(194, 'kons', 'g, k, j, ç', '<kk>', 'regel', 'foran a-, o- og å-lyd ', 'k: ', 'klokka', '', '²kʲʰlɔkːɑ', ''),
(195, 'kons', 'g, k, j, ç', '<kj>', 'regel', '', 'ç', 'kjær', '', '¹çæːɾ', ''),
(196, 'kons', 'g, k, j, ç', '<kj>', 'regel', '', 'ç', 'kjøkken', '', '¹çœkʲːɘn', ''),
(197, 'kons', 'g, k, j, ç', '<kj>', 'regel', '', 'ç', 'kjole', '', '²çuːlə', ''),
(198, 'kons', 'g, k, j, ç', '<c>', 'fremmedord', '', 'k', 'calypso', 'engelsk', 'kɑ¹lʏpːsʊ', ''),
(199, 'kons', 'g, k, j, ç', '<c>', 'fremmedord', '', 'k', 'cowboy', 'engelsk', '¹kʰɔbːɔ͜ɪ', ''),
(200, 'kons', 'g, k, j, ç', '<c>', 'fremmedord', '', 'kʲ', 'croissant', 'fransk', 'kʲɾɔɑ¹sɑŋː', ''),
(201, 'kons', 'g, k, j, ç', '<c>', 'fremmedord', '', 'kʲ', 'cruiseskip', 'engelsk', '¹kʲɾʉːsʃiːpʰ', ''),
(202, 'kons', 'g, k, j, ç', '<cc>', 'fremmedord', '', 'kː', 'al secco', 'italiensk', 'ɑɫ¹sɛk:ɔ', ''),
(203, 'kons', 'g, k, j, ç', '<ch>', 'fremmedord', '', 'k', 'chianti', 'italiensk', 'kʲɪ¹ɑnːtɪ', ''),
(204, 'kons', 'g, k, j, ç', '<ck>', 'fremmedord', '', 'kʲː', 'truck', 'engelsk', '¹tʰɾœkʲʰː', ''),
(205, 'kons', 'g, k, j, ç', '<ck>', 'fremmedord', '', 'kʲː', 'cockpit', 'engelsk', '¹kʰɔkʲːpɪtʰ', ''),
(206, 'kons', 'g, k, j, ç', '<ck>', 'fremmedord', '', 'kʲː', 'feedback', 'engelsk', '¹fiːdbækʲʰː', ''),
(207, 'kons', 'g, k, j, ç', '<ck>', 'fremmedord', '', 'kʲː', 'rock', 'engelsk', '¹rɔkʲʰː', ''),
(208, 'kons', 'g, k, j, ç', '<ck>', 'fremmedord', 'foran a-, o- og å-lyd', 'kː', 'knockout', 'engelsk', '¹nɔkːɑ͜ʊtʰ', ''),
(209, 'kons', 'g, k, j, ç', '<hj>', 'regel', '', 'j', 'hjelpe', '', '²jɛlːpə', ''),
(210, 'kons', 'g, k, j, ç', '<hj>', 'regel', '', 'j', 'hjørne', '', '²jøːɳə', ''),
(211, 'kons', 'g, k, j, ç', '<j>', 'regel', '', 'j', 'jobb', '', '¹jɔbː', ''),
(212, 'kons', 'g, k, j, ç', '<lj>', 'regel', 'i begynnelsen av ord', 'j', 'ljå', '', '¹joː', ''),
(213, 'kons', 'g, k, j, ç', '<lj>', 'regel', 'i begynnelsen av ord', 'j', 'ljuge', '', '²jʉːɡʲə', ''),
(214, 'kons', 'g, k, j, ç', '<lj>', 'regel', 'i begynnelsen av ord', 'j', 'ljome', '', '²juːmə', ''),
(215, 'kons', 'g, k, j, ç', '<qu>', 'regel', '', 'kʲʋ', 'qusling', '', '²kʲʋɪʃːlɪŋ', ''),
(216, 'kons', 'g, k, j, ç', '<qu>', 'regel', '', 'kʲʋ', 'quizen', '', '¹kʲʰʋɪsːn͏ͅ', ''),
(217, 'kons', 'g, k, j, ç', '<tj>', 'regel', '', 'ç', 'tjern', '', '¹çæːɳ', ''),
(218, 'kons', 'g, k, j, ç', '<tj>', 'regel', '', 'ç', 'tjeld', '', '¹çɛlː', ''),
(219, 'kons', 'g, k, j, ç', '<tj>', 'regel', '', 'ç', 'tjukk', '', '¹çʉkʲʰː', ''),
(220, 'kons', 'g, k, j, ç', '<tj>', 'regel', '', 'ç', 'tjære', '', '²çæːɾə', ''),
(221, 'kons', 'g, k, j, ç', '<tj>', 'regel', '', 'ç', 'tjue', '', '²çʉːə', ''),
(222, 'kons', 'd, t', '<tj>', 'unntak', 'i ordet tjene og dets avledninger', 'tj', 'tjene', '', '²tʰjeːnə', ''),
(223, 'kons', 'd, t', '<tj>', 'unntak', 'i ordet tjene og dets avledninger', 'tj', 'tjener', '', '²tʰjeːnɘɾ', ''),
(224, 'kons', 'd, t', '<tj>', 'unntak', 'i ordet tjene og dets avledninger', 'tj', 'tjeneste', '', '²tʰjeːnəstə', ''),
(225, 'kons', 'ks', '<x>', 'regel', '', 'kʲs', 'sex', 'andre', '¹sɛkʲːs', ''),
(226, 'kons', 'ks', '<x>', 'regel', '', 'kʲs', 'marxisme', 'andre', 'mɑɾkʲs¹ɪsːmə', ''),
(227, 'kons', 'ks', '<x>', 'regel', 'i lånord fra fransk', '-', 'grand prix', 'fransk', 'gʲɾɑŋ¹pʰɾiː', ''),
(228, 'kons', 'ks', '<x>', 'regel', 'i lånord fra fransk', '-', 'bordeauxvin ', 'fransk', 'bɔ¹ɖoːʋiːn', ''),
(229, 'kons', 'h', '<h>', 'regel', '', 'h', 'han', '', '¹hɑnː', ''),
(230, 'kons', 'h', '<h>', 'regel', '', 'h', 'hemmelig', '', '²hɛmːəlɪ', ''),
(231, 'kons', 'l', '<l>', 'regel', '', 'l', 'lim', '', '¹liːm', ''),
(232, 'kons', 'l', '<l>', 'regel', '', 'l', 'dele', '', '²deːlə', ''),
(233, 'kons', 'l', '<l>', 'regel', '', 'l', 'sol', '', '¹suːl', ''),
(234, 'kons', 'l', '<l>', 'regel', 'i trykksterk stavelse etter kort vokal foran konsonant', 'lː', 'telt', '', '¹tʰɛlːtʰ', ''),
(235, 'kons', 'l', '<l>', 'regel', 'i trykksterk stavelse etter kort vokal foran konsonant', 'lː', 'elske', '', '¹tʰɛlːtʰ', ''),
(236, 'kons', 'l', '<l>', 'regel', 'i trykksterk stavelse etter kort vokal ɑ, ɔ foran konsonant', 'ɫː', 'falsk', '', '¹fɑɫːskʲʰ', ''),
(237, 'kons', 'l', '<l>', 'regel', 'i trykksterk stavelse etter kort vokal ɑ, ɔ foran konsonant', 'ɫː', 'molte', '', '²mɔɫːtə', ''),
(238, 'kons', 'l', '<l>', 'regel', 'etter ɑː, oː', 'ɫ', 'palme', '', '²pʰɑɫːmə', ''),
(239, 'kons', 'l', '<l>', 'regel', 'etter ɑː, oː', 'ɫ', 'mål', '', '¹moːɫ', ''),
(240, 'kons', 'l', '<l>', 'regel', '<el> i endelsene -el/-else etter d og t uttales med stavelsesbærende l', 'l̩', 'handel', '', '¹hɑnːdl̩', 'kryssreferanse til tilsvarende sted for stum e'),
(241, 'kons', 'l', '<l>', 'regel', '<el> i endelsene -el/-else etter d og t uttales med stavelsesbærende l', 'l̩', 'middel', '', '¹mɪdːl̩', 'kryssreferanse til tilsvarende sted for stum e'),
(242, 'kons', 'l', '<l>', 'regel', '<el> i endelsene -el/-else etter d og t uttales med stavelsesbærende l', 'l̩', 'nytelse', '', '²nyːtl̩sə', 'kryssreferanse til tilsvarende sted for stum e'),
(243, 'kons', 'l', '<l>', 'regel', '<el> i endelsene -el/-else etter d og t uttales med stavelsesbærende l', 'l̩', 'utsettelse', '', '¹ʉːtsɛtːl̩sə', 'kryssreferanse til tilsvarende sted for stum e'),
(244, 'kons', 'l', '<ll>', 'regel', '', 'lː', 'lilla', '', '¹lɪlːɑ', ''),
(245, 'kons', 'l', '<ll>', 'regel', '', 'lː', 'fjell', '', '¹fjɛlː', ''),
(246, 'kons', 'l', '<ll>', 'regel', 'etter ɑ, ɔ', 'ɫː', 'alle', '', '²ɑɫːə', ''),
(247, 'kons', 'l', '<ll>', 'regel', 'etter ɑ, ɔ', 'ɫː', 'bolle', '', '²bɔɫːə', ''),
(248, 'kons', 'l', '<ld>', 'regel', '', 'lː', 'eldst', '', '¹ɛlːst', ''),
(249, 'kons', 'l', '<ld>', 'regel', '', 'lː', 'gjelde', '', '²jɛlːə', ''),
(250, 'kons', 'l', '<ld>', 'regel', '', 'lː', 'kveld', '', '¹kʲʰʋɛlː', ''),
(251, 'kons', 'l', '<ld>', 'regel', 'etter ɑ og ɔ', 'ɫː ', 'Harald', '', '²hɑɾːɑɫː', ''),
(252, 'kons', 'l', '<ld>', 'regel', 'etter ɑ og ɔ', 'ɫː ', 'vold', '', '¹ʋɔɫː', ''),
(253, 'kons', 'l', '<ld>', 'regel', 'etter ɑ og ɔ', 'ɫː ', 'holde', '', '²hɔɫːə', ''),
(254, 'kons', 'l', '<ld>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'lːd', 'bilde', '', '²bɪlːdə', ''),
(255, 'kons', 'l', '<ld>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'ɫːd', 'aldri', '', '²ɑɫːdɾɪ', ''),
(256, 'kons', 'l', '<ld>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'lːd', 'skyldig', '', '²ʃʏlːdɪ', ''),
(257, 'kons', 'l', '<ld>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'lːd', 'gyldig', '', '²jʏlːdɪ', ''),
(258, 'kons', 'l', '<ld>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'lːd', 'tilfeldig', '', 'tʰɪl¹fɛlːdɪ', ''),
(259, 'kons', 'l', '<ld>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'lːd', 'veldig', '', '²ʋɛlːdɪ', ''),
(260, 'kons', 'l', '<lg>', 'unntak', 'stum <g> i <lg> i noen ord (men uttales i helgen, svelge, bølge, m.fl.)', 'lː', 'selge', '', '²sɛlːə', ''),
(261, 'kons', 'l', '<lg>', 'unntak', 'stum <g> i <lg> i noen ord (men uttales i helgen, svelge, bølge, m.fl.)', 'lː', 'følge', '', '²fœlːɘ', ''),
(262, 'kons', 'l', '<rl>', 'regel', '', 'l', 'perle', '', '²pʰæːlə', ''),
(263, 'kons', 'l', '<rl>', 'regel', '', 'l', 'alvorlig', '', 'ɑɫ¹ʋoːlɪ', ''),
(264, 'kons', 'l', '<rl>', 'regel', '', 'l', 'dårlig', '', '²doːlɪ', ''),
(265, 'kons', 'm, n, ŋ', '<m>', 'regel', '', 'm', 'melk', '', '¹mɛlːkʲʰ', ''),
(266, 'kons', 'm, n, ŋ', '<m>', 'regel', '', 'm', 'ambulanse', '', 'ɑmbʉ¹lɑŋːsə', ''),
(267, 'kons', 'm, n, ŋ', '<m>', 'regel', '', 'm', 'monogam', '', 'mʊnʊ¹gɑːm', ''),
(268, 'kons', 'm, n, ŋ', '<m>', 'regel', 'ofte i slutten av ord etter kort vokal, og foran andre konsonanter i trykksterk stavelse', 'mː', 'strøm', '', '¹stɾœmː', ''),
(269, 'kons', 'm, n, ŋ', '<m>', 'regel', 'ofte i slutten av ord etter kort vokal, og foran andre konsonanter i trykksterk stavelse', 'mː', 'berømte', '', 'bɛ¹ɾœmːtə', ''),
(270, 'kons', 'm, n, ŋ', '<m>', 'regel', 'ofte i slutten av ord etter kort vokal, og foran andre konsonanter i trykksterk stavelse', 'mː', 'femten', '', '²fɛmːtn͏ͅ', ''),
(271, 'kons', 'm, n, ŋ', '<m>', 'regel', 'ofte i slutten av ord etter kort vokal, og foran andre konsonanter i trykksterk stavelse', 'mː', 'Tromsø', '', '²tʰɾʊmːsœ', ''),
(272, 'kons', 'm, n, ŋ', '<mm>', 'regel', '', 'mː', 'mamma', '', '²mɑmːɑ', ''),
(273, 'kons', 'm, n, ŋ', '<mm>', 'regel', '', 'mː', 'Glomma', '', '²gʲlɔmːɑ', ''),
(274, 'kons', 'm, n, ŋ', '<n>', 'regel', '', 'n', 'nynne', '', '²nʏnːə', ''),
(275, 'kons', 'm, n, ŋ', '<n>', 'regel', '', 'n', 'gnage', '', '²gʲnɑːgʲə', ''),
(276, 'kons', 'm, n, ŋ', '<n>', 'regel', '', 'n', 'klubben', '', '¹kʲʰlʉbːən', ''),
(277, 'kons', 'm, n, ŋ', '<n>', 'regel', 'Etter kort vokal og foran konsonant', 'nː ', 'begynte', '', 'bɛ¹jʏnːtə', ''),
(278, 'kons', 'm, n, ŋ', '<n>', 'regel', 'Etter kort vokal og foran konsonant', 'nː ', 'ansvar', '', '²ɑnːsʋɑːɾ', ''),
(279, 'kons', 'm, n, ŋ', '<n>', 'regel', 'foran b og p', 'm', 'anbefale', '', '¹ɑmːbəfɑːɫə', ''),
(280, 'kons', 'm, n, ŋ', '<n>', 'regel', 'foran b og p', 'm', 'tannpasta', '', '²tʰɑmːpɑstɑ', ''),
(281, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'dyden', '', '¹dyːdnͅ', 'kryssreferanse til tilsvarende sted for stum e'),
(282, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'ballen', '', '¹bɑɫːnͅ', 'kryssreferanse til tilsvarende sted for stum e'),
(283, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'mannen', '', '¹mɑnːnͅ', 'kryssreferanse til tilsvarende sted for stum e'),
(284, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'posen', '', '²pʰuːsnͅ', 'kryssreferanse til tilsvarende sted for stum e'),
(285, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'gutten', '', '¹gʲʉːtnͅ', 'kryssreferanse til tilsvarende sted for stum e'),
(286, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'badene', '', '¹bɑːdn̩ə', 'kryssreferanse til tilsvarende sted for stum e'),
(287, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'fuglene', '', '²fʉːln͏ͅə', 'kryssreferanse til tilsvarende sted for stum e'),
(288, 'kons', 'm, n, ŋ', '<n>', 'regel', '<en> i endelsene -en/-ene etter d, t, n og s uttales med stavelsesbærende n', 'nͅ', 'guttene', '', '²gʲʉtːn͏ͅə', 'kryssreferanse til tilsvarende sted for stum e'),
(289, 'kons', 'm, n, ŋ', '<nn>', 'regel', '', 'nː', 'kanne', '', '²kʰɑnːə', ''),
(290, 'kons', 'm, n, ŋ', '<nn>', 'regel', '', 'nː', 'banne', '', '²bɑnːə', ''),
(291, 'kons', 'm, n, ŋ', '<nn>', 'regel', '', 'nː', 'lønna', '', '¹lœnːɑ', ''),
(292, 'kons', 'm, n, ŋ', '<nn>', 'spesiell uttale', '', '-', 'annen          ', '', '²ɑːɑn', ''),
(293, 'kons', 'm, n, ŋ', '<nn>', 'spesiell uttale', '', '-', 'annet', '', '²ɑːɑntʰ ', ''),
(294, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː ', 'land', '', '¹lɑnː', ''),
(295, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː ', 'skynde', '', '²ʃʏn:ə', ''),
(296, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː ', 'vondt', '', '¹ʋʊnːtʰ', ''),
(297, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː ', 'binde', '', '²bɪnːə', ''),
(298, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː ', 'hund', '', '¹hʉnː', ''),
(299, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː ', 'bonde', '', '²bʊnːə', ''),
(300, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː', 'and', '', '¹ɑnː', ''),
(301, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː', 'binde', '', '²bɪnːə', ''),
(302, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksterk stavelse', 'nː', 'bonde', '', '²bʊnːə', ''),
(303, 'kons', 'm, n, ŋ', '<nd>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'nːd', 'bande', '', '²bɑnːdə', ''),
(304, 'kons', 'm, n, ŋ', '<nd>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'nːd', 'mindre', '', '¹mɪnːdɾə', ''),
(305, 'kons', 'm, n, ŋ', '<nd>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'nːd', 'hundre', '', '²hʉnːdɾə', ''),
(306, 'kons', 'm, n, ŋ', '<nd>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'nːd', 'handle', '', '²hɑnːdlə', ''),
(307, 'kons', 'm, n, ŋ', '<nd>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'nːd', 'andre', '', '²ɑnːdɾə', ''),
(308, 'kons', 'm, n, ŋ', '<nd>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'nːd', 'forandre', '', 'fɔɾ¹ɑnːdɾə', ''),
(309, 'kons', 'm, n, ŋ', '<nd>', 'unntak', 'd uttales i noen ord der d ikke står til slutt', 'nːd ', 'andre', '', '²ɑnːdɾə', ''),
(310, 'kons', 'm, n, ŋ', '<nd>', 'fremmedord', '', 'nːd ', 'behandle', 'tysk', 'bɛ¹hɑnːdlə', ''),
(311, 'kons', 'm, n, ŋ', '<nd>', 'fremmedord', '', 'nːd ', 'hinduisme', 'tysk', 'hɪndʉ¹ɪsːmə', ''),
(312, 'kons', 'm, n, ŋ', '<nd>', 'fremmedord', '', 'nːd ', 'agenda', 'latin', 'ɑ¹gʲɛnːdɑ', ''),
(313, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksvak stavelse', 'n ', 'levende', '', '²leːʋənə', ''),
(314, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksvak stavelse', 'n ', 'undervisning', '', 'ʉnə¹ʋiːsniŋː', ''),
(315, 'kons', 'm, n, ŋ', '<nd>', 'regel', 'i trykksvak stavelse', 'n ', 'Eivind', '', '²æ͜ɪʋɪn', ''),
(316, 'kons', 'm, n, ŋ', '<ng>', 'regel', 'i trykksvak stavelse', 'ŋ', 'delingen', '', '²deːlɪŋɘn', ''),
(317, 'kons', 'm, n, ŋ', '<ng>', 'regel', '', 'ŋː', 'mange', '', '²mɑŋːə', ''),
(318, 'kons', 'm, n, ŋ', '<ng>', 'regel', '', 'ŋː', 'balkong', '', 'bɑɫ¹kʰɔŋː', ''),
(319, 'kons', 'm, n, ŋ', '<ng>', 'regel', '', 'ŋː', 'tilgjengelig', '', 'tʰɪl¹jɛŋːəlɪ', ''),
(320, 'kons', 'm, n, ŋ', '<ng>', 'regel', '', 'ŋː', 'lunger', '', '²lʊŋːɘɾ', ''),
(321, 'kons', 'm, n, ŋ', '<ng>', 'fremmedord', '', 'ŋːg', 'tango', 'spansk', '¹tʰɑŋːgʊ', ''),
(322, 'kons', 'm, n, ŋ', '<ng>', 'fremmedord', '', 'ŋːg', 'mango', 'portugisisk', '¹mɑŋːgʊ', ''),
(323, 'kons', 'm, n, ŋ', '<nk>', 'regel', '', 'ŋːk', 'bank', '', '¹bɑŋːkʲ', ''),
(324, 'kons', 'm, n, ŋ', '<gn>', 'regel', 'men ikke etter e og ø ', 'ŋːn', 'sagn', '', '¹sɑŋːn', ''),
(325, 'kons', 'm, n, ŋ', '<gn>', 'regel', 'men ikke etter e og ø ', 'ŋːn', 'agn', '', '¹ɑŋːn', ''),
(326, 'kons', 'm, n, ŋ', '<gn>', 'regel', 'men ikke etter e og ø ', 'ŋːn', 'Magne', '', '²mɑŋːnə', ''),
(327, 'kons', 'm, n, ŋ', '<gn>', 'regel', 'men ikke etter e og ø ', 'ŋːn', 'Sogn', '', '¹sɔŋːn', ''),
(328, 'kons', 'm, n, ŋ', '<nt>', 'fremmedord', 'i slutten av lånord fra fransk', 'ŋː', 'restaurant', 'fransk', 'ɾɛstʉ¹ɾɑŋː', ''),
(329, 'kons', 'm, n, ŋ', '<nt>', 'fremmedord', 'i slutten av lånord fra fransk', 'ŋː', 'arrangement', 'fransk', 'ɑɾɑŋʃə¹mɑŋː', ''),
(330, 'kons', 'm, n, ŋ', '<nt>', 'fremmedord', 'i slutten av lånord fra fransk', 'ŋː', 'departement', 'fransk', 'dɛpɑʈə¹mɑŋː', ''),
(331, 'kons', 'm, n, ŋ', '<nt>', 'fremmedord', 'i slutten av lånord fra fransk', 'ŋː', 'presentere', 'fransk', 'pʰɾɛsɑŋ¹tʰeːɾə', ''),
(332, 'kons', 'm, n, ŋ', '<nt>', 'fremmedord', 'i slutten av lånord fra fransk', 'ŋː', 'croissant', 'fransk', 'kɾɔɑ¹sɑŋː', ''),
(333, 'kons', 'm, n, ŋ', '<nt>', 'fremmedord', 'i slutten av lånord fra fransk', 'ŋː', 'interessant (mask. og fem.)', 'fransk', 'ɪntɾə¹sɑŋː', 'merk uttaleforskjell avhengig av kjønn'),
(334, 'kons', 'm, n, ŋ', '<nt>', 'fremmedord', 'i slutten av lånord fra fransk', 'ŋː', 'interessant (nøytr.)', 'fransk', 'ɪntɾə¹sɑŋːtʰ', 'merk uttaleforskjell avhengig av kjønn'),
(335, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'ambulanse', 'fransk', 'ɑmbʉ¹lɑŋːsə', ''),
(336, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'kompetanse', 'fransk', 'kʰʊmpə¹tʰɑŋːsə', ''),
(337, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'konkurranse', 'fransk', 'kʰʊŋkʰʉ¹ɾɑŋːsə', ''),
(338, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'balanse', 'fransk', 'bɑ¹lɑŋːsə', ''),
(339, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'distanse', 'fransk', 'dɪ¹stɑŋːsə', ''),
(340, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'konferanse', 'fransk', 'kʰʊmfə¹ɾɑŋːsə', ''),
(341, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'toleranse', 'fransk', 'tʰɔɫə¹ɾɑŋːsə', ''),
(342, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'nyanse', 'fransk', 'nʏ¹ɑŋːsə', ''),
(343, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'sjanse', 'fransk', '²ʃɑŋːsə', ''),
(344, 'kons', 'm, n, ŋ', '<ns>', 'fremmedord', 'etter a i lånord fra fransk', 'ŋːs', 'referanse', 'fransk', 'ɾɛfə¹ɾɑŋːsə', ''),
(345, 'kons', 'm, n, ŋ', '<nsj>', 'fremmedord', '', 'ŋːʃ / ŋʃ', 'bransje', 'fransk', '²bɾɑŋːʃə', ''),
(346, 'kons', 'm, n, ŋ', '<nsj>', 'fremmedord', '', 'ŋːʃ / ŋʃ', 'pensjon', 'fransk', 'pʰɑŋ¹ʃuːn', ''),
(347, 'kons', 'm, n, ŋ', '<nsj>', 'fremmedord', '', 'ŋːʃ / ŋʃ', 'oransje', 'fransk', 'ʊ¹ɾɑŋːʃə', ''),
(348, 'kons', 'm, n, ŋ', '<nsj>', 'fremmedord', '', 'ŋːʃ / ŋʃ', 'plansje', 'fransk', '²pʰlɑŋːʃə', ''),
(349, 'kons', 'm, n, ŋ', '<nsj>', 'fremmedord', '', 'ŋːʃ / ŋʃ', 'prevensjon', 'latin', 'pʰɾəʋɑŋ¹ʃuːn', ''),
(350, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', '', 'ɾ', 'ribbe', '', '²ɾɪbːə', ''),
(351, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', '', 'ɾ', 'satire', '', 'sɑ²tʰiːɾə', ''),
(352, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', '', 'ɾ', 'administrator', '', 'ɑdmɪnɪ¹stɾɑːtʊɾ', ''),
(353, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'etter kort vokal foran konsonant i trykksterk stavelse', 'ɾː ', 'rabarbra', '', 'ɾɑ¹bɑɾːbɾɑ', ''),
(354, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'etter kort vokal foran konsonant i trykksterk stavelse', 'ɾː ', 'armen', '', '¹ɑɾːmɘn', ''),
(355, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'etter kort vokal foran konsonant i trykksterk stavelse', 'ɾː ', 'verpe', '', '²ʋæɾːpə', ''),
(356, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom a/ø/æ og endelsen -else', '-', 'besparelse', '', 'bɛ¹spɑːɑlsə', 'assimilasjon av første e i -else'),
(357, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom a/ø/æ og endelsen -else', '-', 'besvarelse', '', 'bɛ¹sʋɑːɑlsə', 'assimilasjon av første e i -else'),
(358, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom a/ø/æ og endelsen -else', '-', 'avgjørelse', '', '¹ɑːʋjøːl̩sə', 'assimilasjon av første e i -else'),
(359, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom a/ø/æ og endelsen -else', '-', 'framførelse', '', '¹fɾɑmːføːl̩sə', 'assimilasjon av første e i -else'),
(360, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom a/ø/æ og endelsen -else', '-', 'kunngjørelse', '', '²kʲʰʉnːjøːl̩sə', 'assimilasjon av første e i -else'),
(361, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom a/ø/æ og endelsen -else', '-', 'værelse', '', '²ʋæːlsə', 'assimilasjon av første e i -else'),
(362, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'faren', '', '²fɑːɑɳ', 'assimilasjon av e i -en'),
(363, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'uerfaren', '', '²ʉːæɾfɑːɑɳ', 'assimilasjon av e i -en'),
(364, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'vikaren', '', 'ʋɪ¹kʰɑːɑɳ', 'assimilasjon av e i -en'),
(365, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'fakiren', '', 'fɑ¹kʲʰiːɪɳ', 'assimilasjon av e i -en'),
(366, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'kefiren', '', '¹kʲʰeːfiːɪɳ', 'assimilasjon av e i -en'),
(367, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'safiren', '', 'sɑ¹fiːɪɳ', 'assimilasjon av e i -en'),
(368, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'moren', '', '²muːʊɳ', 'assimilasjon av e i -en'),
(369, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'majoren', '', 'mɑ¹juːʊɳ', 'assimilasjon av e i -en'),
(370, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'broren', '', '²bɾuːʊɳ', 'assimilasjon av e i -en'),
(371, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'naturen', '', 'nɑ¹tʰʉːʉɳ', 'assimilasjon av e i -en'),
(372, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'kulturen', '', 'kʰʉl¹tʰʉːʉɳ', 'assimilasjon av e i -en'),
(373, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'muren', '', '¹mʉːʉɳ', 'assimilasjon av e i -en'),
(374, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'komfyren', '', 'kʰʊm¹fyːʏɳ', 'assimilasjon av e i -en'),
(375, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'fyren', '', '¹fyːʏɳ', 'assimilasjon av e i -en'),
(376, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'vampyren', '', 'ʋɑm¹pʰyːʏɳ', 'assimilasjon av e i -en'),
(377, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'sekretæren', '', 'sɛkʲɾɛ¹tʰæːæɳ', 'assimilasjon av e i -en'),
(378, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'hæren', '', '¹hæːæɳ', 'assimilasjon av e i -en'),
(379, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'gjæren', '', '¹jæːæɳ', 'assimilasjon av e i -en'),
(380, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'døren', '', '¹døːœɳ', 'assimilasjon av e i -en'),
(381, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'ambassadøren', '', 'ɑmbɑsɑ¹døːœɳ', 'assimilasjon av e i -en'),
(382, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'markøren', '', 'mɑɾ¹kʲʰøːœɳ', 'assimilasjon av e i -en'),
(383, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'måren', '', '¹moːɔɳ', 'assimilasjon av e i -en'),
(384, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'våren', '', '¹ʋoːɔɳ', 'assimilasjon av e i -en'),
(385, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'åren', '', '²oːɔɳ', 'assimilasjon av e i -en'),
(386, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -en', '-', 'gården', '', '¹goːɔɳ', 'assimilasjon av e i -en'),
(387, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom diftong og endelsen -en', '-', 'mauren', '', '¹mæ͜ʉæɳ', 'assimilasjon av e i -en'),
(388, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom diftong og endelsen -en', '-', 'leiren', '', '¹læ͜ɪæɳ', 'assimilasjon av e i -en'),
(389, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'i ordet morgen gjelder det samme som mellom vokal og endelsen -en', '-', 'morgen, morgenen, morgener, morgenene ', '', '²moːɔɳ, ²moːɔɳɳͅ, ²moːɔɳɘɾ, ²moːɔɳɳͅə', 'assimilasjon av e i -en'),
(390, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksvak o og endelsen -en blir også e-en i endelsen borte', '-', 'motoren', '', '¹muːtʊɳ', 'assimilasjon av e i -en'),
(391, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksvak o og endelsen -en blir også e-en i endelsen borte', '-', 'eksaminatoren', '', 'ɛkʲsɑmɪ¹nɑːtʊɳ', 'assimilasjon av e i -en'),
(392, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksvak o og endelsen -en blir også e-en i endelsen borte', '-', 'kalkulatoren', '', 'kʰɑɫkʲʰʉ¹lɑːtʊɳ', 'assimilasjon av e i -en'),
(393, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'gitarene', '', 'gʲɪ¹tʰɑːɑɳə', 'assimilasjon av første e i -ene'),
(394, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'kommentarene', '', 'kʰʊmən¹tʰɑːɑɳə', 'assimilasjon av første e i -ene'),
(395, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'bibliotekarene', '', 'bɪblɪʊtʰɛ¹kʰɑːɑɳə', 'assimilasjon av første e i -ene'),
(396, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'fakirene', '', 'fɑ¹kʲʰiːɪɳə', 'assimilasjon av første e i -ene'),
(397, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'papirene', '', 'pʰɑ¹pʰiːɪɳə', 'assimilasjon av første e i -ene'),
(398, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'girene', '', '¹gʲiːɪɳə', 'assimilasjon av første e i -ene'),
(399, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'teonorene', '', 'tʰɛ¹nuːʊɳə', 'assimilasjon av første e i -ene'),
(400, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'kontorene', '', 'kʰʊn¹tʰuːʊɳə', 'assimilasjon av første e i -ene'),
(401, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'majorene', '', 'mɑ¹juːʊɳə', 'assimilasjon av første e i -ene'),
(402, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'murene', '', '²mʉːʉɳə', 'assimilasjon av første e i -ene'),
(403, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'kulturene', '', 'kʰʉl¹tʰʉːʉɳə', 'assimilasjon av første e i -ene'),
(404, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'turene', '', '²tʰʉːʉɳə', 'assimilasjon av første e i -ene'),
(405, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'komfyrene', '', 'kʰʊm¹fyːʏɳə', 'assimilasjon av første e i -ene'),
(406, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'vampyrene', '', 'ʋɑm¹pʰyːʏɳə', 'assimilasjon av første e i -ene'),
(407, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'dyrene', '', '¹dyːʏɳə', 'assimilasjon av første e i -ene'),
(408, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'sekretærene', '', 'sɛkʲɾɛ¹tʰæːæɳə', 'assimilasjon av første e i -ene'),
(409, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'geværene', '', 'gʲɛ¹ʋæːæɳə', 'assimilasjon av første e i -ene'),
(410, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'hærene', '', '²hæːæɳə', 'assimilasjon av første e i -ene'),
(411, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'frisørene', '', 'fɾɪ¹søːœɳə', 'assimilasjon av første e i -ene'),
(412, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'dørene', '', '²døːœɳə', 'assimilasjon av første e i -ene'),
(413, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'ambassadørene', '', 'ɑmbɑsɑ¹døːœɳə', 'assimilasjon av første e i -ene'),
(414, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'sårene', '', '¹soːɔɳə', 'assimilasjon av første e i -ene'),
(415, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'hårene', '', '¹hoːɔɳə', 'assimilasjon av første e i -ene'),
(416, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'vilkårene', '', '²ʋɪlːkʰoːɔɳə', 'assimilasjon av første e i -ene'),
(417, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom vokal og endelsen -ene', '-', 'gårdene', '', '²goːɔɳə', 'assimilasjon av første e i -ene'),
(418, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksvak o og endelsen -ene blir også e-en i endelsen borte', '-', 'motorene', '', '¹muːtʊɳə', 'assimilasjon av første e i -ene'),
(419, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksvak o og endelsen -ene blir også e-en i endelsen borte', '-', 'eksaminatorene', '', 'ɛkʲsɑmɪ¹nɑːtʊɳə', 'assimilasjon av første e i -ene'),
(420, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksvak o og endelsen -ene blir også e-en i endelsen borte', '-', 'kalkulatorene', '', 'kʰɑɫkʲʰʉ¹lɑːtʊɳə', 'assimilasjon av første e i -ene'),
(421, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom diftong og endelsen -ene', '-', 'maurene ', '', '¹mæ͜ʉæɳə', 'assimilasjon av første e i -ene'),
(422, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksterk e endelsen -ende', '-', 'dominerende', '', 'dʊmɪ¹neːɛɳə', ''),
(423, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksterk e endelsen -ende', '-', 'graverende', '', 'gʲɾɑ¹ʋeːɛɳə', ''),
(424, 'kons', 'r, ɖ, ʈ, ɳ', '<r>', 'regel', 'mellom trykksterk e endelsen -ende', '-', 'imponerende', '', 'ɪmpʊ¹neːɛɳə', ''),
(425, 'kons', 'r, ɖ, ʈ, ɳ', '<rr>', 'regel', '', 'ɾː', 'arr', '', '¹ɑɾː', ''),
(426, 'kons', 'r, ɖ, ʈ, ɳ', '<rr>', 'regel', '', 'ɾː', 'kjerre', '', '²çæɾːə', ''),
(427, 'kons', 'r, ɖ, ʈ, ɳ', '<rr>', 'regel', '', 'ɾː', 'større', '', '¹stœɾːə', ''),
(428, 'kons', 'r, ɖ, ʈ, ɳ', '<rr>', 'regel', 'i trykksvake stavelser', 'ɾ', 'arrangement', '', 'ɑɾɑŋʃə¹mɑŋː', ''),
(429, 'kons', 'r, ɖ, ʈ, ɳ', '<rr>', 'regel', 'i trykksvake stavelser', 'ɾ', 'konkurranse', '', 'kʰʊŋkʰʉ¹ɾɑŋːsə', ''),
(430, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', '', 'ɖ', 'verdi', '', 'ʋæ¹ɖiː', ''),
(431, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', '', 'ɖ', 'hvordan', '', '¹ʋʊɖːɑn', ''),
(432, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', '', 'ɖ', 'ferdig', '', '²fæːɖɪ', ''),
(433, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', '', 'ɖ', 'fordi', '', 'fʊ¹ɖiː', ''),
(434, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', '', 'ɖ', 'gardin', '', 'gɑ¹ɖiːn', ''),
(435, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', '', 'ɖ', 'Hardanger', '', 'hɑ¹ɖɑŋːɘɾ', ''),
(436, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', 'i trykksvak posisjon', 'ɾd', 'samordne', '', '²sɑmːɔɾdnə', ''),
(437, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', 'etter lang vokal', 'ɾ', 'fjord', '', '¹fjuːɾ', ''),
(438, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', 'etter lang vokal', 'ɾ', 'bord', '', '¹buːɾ', ''),
(439, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', 'etter lang vokal', 'ɾ', 'ord', '', '¹uːɾ', ''),
(440, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', 'etter lang vokal', 'ɾ', 'nord', '', '¹nuːɾ', ''),
(441, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', 'etter lang vokal', 'ɾ', 'hard', '', '¹hɑːɾ', ''),
(442, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'regel', 'etter lang vokal', 'ɾ', 'gjorde, jorde', '', '²juːɾə', ''),
(443, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'verden', '', '¹ʋæɾːdnͅ', ''),
(444, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'Norden', '', '¹nʊɾːdn̩', ''),
(445, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'torden', '', '¹tʰʊɾːdn̩', ''),
(446, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'ferden', '', '¹fæɾːdnͅ', ''),
(447, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'mord', '', '¹mʊɾːd', ''),
(448, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'morder', '', '²mʊɾːdɘɾ', ''),
(449, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'myrde', '', '²mʏɾːdə', ''),
(450, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'severdighet', '', 'sɛ¹ʋæɾːdɪhɛːtʰ', ''),
(451, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'verdig', '', '²ʋæɾːdɪ', ''),
(452, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'ordne', '', '²ɔɾːdnə', ''),
(453, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'orden', '', '¹ɔɾːdn̩', ''),
(454, 'kons', 'r, ɖ, ʈ, ɳ', '<rd>', 'unntak', '', 'ɾːd', 'lærd', '', '¹læɾːd', ''),
(455, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'etter lang vokal', 'ʈ', 'arrangerte', '', 'ɑɾɑŋ¹ʃeːʈə', ''),
(456, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'etter kort vokal i trykksterk stavelse', 'ʈː', 'hjerte', '', '²jæʈːə', ''),
(457, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'etter kort vokal i trykksterk stavelse', 'ʈː', 'erta', '', '¹æʈːɑ', ''),
(458, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'etter kort vokal i trykksterk stavelse', 'ʈː', 'departement', '', 'dɛpɑʈə¹mɑŋː', ''),
(459, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'i begynnelsen av trykksterke stavelser og i slutten av ord', 'ʈʰ ', 'artikkel', '', 'ɑ¹ʈʰɪkʲːɘl', ''),
(460, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'i begynnelsen av trykksterke stavelser og i slutten av ord', 'ʈʰ ', 'fortelle', '', 'fɔ¹ʈʰɛlːə', ''),
(461, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'i begynnelsen av trykksterke stavelser og i slutten av ord', 'ʈʰ ', 'avansert', '', 'ɑʋɑŋ¹seːʈʰ', ''),
(462, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'regel', 'i begynnelsen av trykksterke stavelser og i slutten av ord', 'ʈʰ ', 'bort', '', '¹bʊʈʰː', ''),
(463, 'kons', 'r, ɖ, ʈ, ɳ', '<rt>', 'fremmedord', '', 'r', 'dessert', 'fransk', 'dɛ¹sæːɾ', ''),
(464, 'kons', 'r, ɖ, ʈ, ɳ', '<rds>', 'regel', '<rd> uttales som <rt> foran s hvis rd uttales som ɖ i det  samme ordet uten s (se der)', 'ʈːʃ / ʈʃ', 'ferdsel', '', '¹fæʈːʃɘl', ''),
(465, 'kons', 'r, ɖ, ʈ, ɳ', '<rds>', 'regel', '<rd> uttales som <rt> foran s hvis rd uttales som ɖ i det  samme ordet uten s (se der)', 'ʈːʃ / ʈʃ', 'adferdsvanske', '', '²ɑːdfæʈʃʋɑnːskʲə', ''),
(466, 'kons', 'r, ɖ, ʈ, ɳ', '<rdt>', 'regel', '', 'ʈː / ʈ', 'hardt', '', '¹hɑʈː', ''),
(467, 'kons', 'r, ɖ, ʈ, ɳ', '<rdt>', 'regel', '', 'ʈː / ʈ', 'verdt', '', '¹ʋæʈʰː', ''),
(468, 'kons', 'r, ɖ, ʈ, ɳ', '<rdt>', 'regel', '', 'ʈː / ʈ', 'bordtennis', '', '²buːʈʰɛnːɪs', ''),
(469, 'kons', 'r, ɖ, ʈ, ɳ', '<rdt>', 'regel', '', 'ʈː / ʈ', 'ordtak', '', '²uːʈʰɑːkʲ', ''),
(470, 'kons', 'r, ɖ, ʈ, ɳ', '<rkt>', 'regel', '', 'ʈː / ʈʰː', 'mørkt', '', '¹mœʈʰː', 'alternativ uttale: ɾːkʲtʰ'),
(471, 'kons', 'r, ɖ, ʈ, ɳ', '<rkt>', 'regel', '', 'ʈː / ʈʰː', 'sterkt', '', '¹stœʈʰː', 'alternativ uttale: ɾːkʲtʰ'),
(472, 'kons', 'r, ɖ, ʈ, ɳ', '<rkt>', 'regel', '', 'ʈː / ʈʰː', 'verktøy', '', '¹ʋæʈːœ͜ʏ', 'alternativ uttale: ɾːkʲtʰ'),
(473, 'kons', 'r, ɖ, ʈ, ɳ', '<rn>', 'regel', '', 'ɳ ', 'korn', '', '¹kʰuːɳ', ''),
(474, 'kons', 'r, ɖ, ʈ, ɳ', '<rn>', 'regel', '', 'ɳ ', 'barn', '', '¹bɑːɳ', ''),
(475, 'kons', 'r, ɖ, ʈ, ɳ', '<rn>', 'regel', '', 'ɳ ', 'fyrtårn', '', '¹fyːʈoːɳ', ''),
(476, 'kons', 'r, ɖ, ʈ, ɳ', '<rn>', 'regel', '', 'ɳ ', 'ekorn ', '', '²ɛkʲːʊɳ', ''),
(477, 'kons', 'r, ɖ, ʈ, ɳ', '<rn>', 'regel', '', 'ɳ ', 'overnatte', '', '²oːʋɘɳɑtːɘ', ''),
(478, 'kons', 'r, ɖ, ʈ, ɳ', '<rn>', 'regel', '', 'ɳ ', 'Ungarn', '', '¹ʊŋːɡɑɳ', ''),
(479, 'kons', 'r, ɖ, ʈ, ɳ', '<en>', 'regel', 'i trykksvake stavelser etter <rt>', 'ɳ̩', 'kikkerten', '', '¹çɪkʲːəʈɳ̩', ''),
(480, 'kons', 'r, ɖ, ʈ, ɳ', '<en>', 'regel', 'i trykksvake stavelser etter <rt>', 'ɳ̩', 'ertene', '', '¹æʈːɳ̩ə', ''),
(481, 'kons', 'r, ɖ, ʈ, ɳ', '<en>', 'regel', 'i trykksvake stavelser etter <rt>', 'ɳ̩', 'kikkertene', '', '¹çɪkʲːəʈɳ̩ə', ''),
(482, 'kons', 'r, ɖ, ʈ, ɳ', '<nsj>', 'regel', 'foran <sj>', 'ɳːʃ', 'lunsj', '', '¹lœɳːʃ', ''),
(483, 'kons', 'r, ɖ, ʈ, ɳ', '<nsj>', 'regel', 'foran <sj>', 'ɳːʃ', 'punsj', '', '¹pʰœɳːʃ', ''),
(484, 'kons', 'r, ɖ, ʈ, ɳ', '<nsj>', 'regel', 'foran <sj>', 'ɳːʃ', 'lynsje', '', '²lʏɳːʃə', ''),
(485, 'kons', 'r, ɖ, ʈ, ɳ', '<nsj>', 'regel', 'foran <sj>', 'ɳːʃ', 'vinsj', '', '¹ʋɪɳːʃ', ''),
(486, 'kons', 'r, ɖ, ʈ, ɳ', '<nskj>', 'regel', 'foran <skj>', 'ɳːʃ', 'kanskje', '', '¹kɑɳːʃə', ''),
(487, 'kons', 'r, ɖ, ʈ, ɳ', '<-eren>', 'regel', '', 'æɳ', 'sommeren', '', '²sɔmːæɳ', ''),
(488, 'kons', 'r, ɖ, ʈ, ɳ', '<-eren>', 'regel', '', 'æɳ', 'latvieren', '', '¹lɑtːʋɪæɳ', ''),
(489, 'kons', 'r, ɖ, ʈ, ɳ', '<-eren>', 'regel', '', 'æɳ', 'giveren', '', '²jiːʋæɳ', ''),
(490, 'kons', 'r, ɖ, ʈ, ɳ', '<-eren>', 'regel', '', 'æɳ', 'jegeren', '', '²jeːɡʲæɳ', ''),
(491, 'kons', 'r, ɖ, ʈ, ɳ', '<-erne>', 'regel', '', 'æɳə', 'latvierne', '', '¹lɑtːʋɪæɳə', ''),
(492, 'kons', 'r, ɖ, ʈ, ɳ', '<-erne>', 'regel', '', 'æɳə', 'jegerne', '', '²jeːɡʲæɳə', ''),
(493, 'kons', 'r, ɖ, ʈ, ɳ', '<-erne>', 'regel', '', 'æɳə', 'krigerne', '', '²kʲʰɾiːgʲæɳə', ''),
(494, 'kons', 'r, ɖ, ʈ, ɳ', '<-erne>', 'regel', '', 'æɳə', 'lærerne', '', '²læːɾæɳə', ''),
(495, 'kons', 'r, ɖ, ʈ, ɳ', '<rmt>', 'spesiell uttale', 'i ordet varmt og kombinasjoner med dette ordet', 'ɳːʈ', 'varmt', '', '¹vɑɳːʈ ', 'alternativ uttale: ¹ʋɑɾːmtʰ'),
(496, 'kons', 's, ​ʃ', '<s>', 'regel', '', 's', 'skap', '', '¹skɑːp', ''),
(497, 'kons', 's, ​ʃ', '<s>', 'regel', 'etter kort vokal foran konsonant', 'sː', 'fantastisk', '', 'fɑn¹tʰɑsːtɪskʲ', ''),
(498, 'kons', 's, ​ʃ', '<s>', 'regel', 'etter kort vokal foran konsonant', 'sː', 'marksisme', '', 'mɑɾkʲs¹ɪsːmə', ''),
(499, 'kons', 's, ​ʃ', '<s>', 'regel', 'etter kort vokal foran konsonant', 'sː', 'Kasper', '', '¹kʰɑsːpɘɾ', ''),
(500, 'kons', 's, ​ʃ', '<s>', 'regel', 'foran l', 'ʃ', 'slem', '', '¹ʃlɛmː', ''),
(501, 'kons', 's, ​ʃ', '<s>', 'regel', 'foran l', 'ʃ', 'sladre', '', '²ʃlɑdːɾə', ''),
(502, 'kons', 's, ​ʃ', '<s>', 'regel', 'foran l', 'ʃ', 'slike', '', '²ʃliːkʲə', ''),
(503, 'kons', 's, ​ʃ', '<s>', 'regel', 'foran l', 'ʃ', 'fengslene', '', '¹fɛŋːʃlənə', ''),
(504, 'kons', 's, ​ʃ', '<s>', 'regel', 'foran l etter kort vokal i trykksterk stavelse', 'ʃː', 'rusle', '', '²ɾʉʃːlə', ''),
(505, 'kons', 's, ​ʃ', '<s>', 'regel', 'foran l etter kort vokal i trykksterk stavelse', 'ʃː', 'Oslo', '', '²ʊʃːlʊ', ''),
(506, 'kons', 's, ​ʃ', '<s>', 'unntak', 'foran l i sammensetninger med f.eks. mis-, is- og andre sammensetninger', 'sːl ', 'mislykket', '', '²mɪsːlʏkʲːətʰ', ''),
(507, 'kons', 's, ​ʃ', '<s>', 'unntak', 'foran l i sammensetninger med f.eks. mis-, is- og andre sammensetninger', 'sːl ', 'mislike', '', '²mɪsːliːkʲə', ''),
(508, 'kons', 's, ​ʃ', '<s>', 'unntak', 'foran l i sammensetninger med f.eks. mis-, is- og andre sammensetninger', 'sːl ', 'islandsk', '', '¹iːslɑnskʲʰ', ''),
(509, 'kons', 's, ​ʃ', '<s>', 'unntak', '', 'sːl', 'Russland ', '', '¹ɾʉsːlɑnː ', 'alternativ uttale: ʃːl'),
(510, 'kons', 's, ​ʃ', '<ss>', 'regel', '', 'sː', 'masse', '', '²mɑsːə', ''),
(511, 'kons', 's, ​ʃ', '<sj>', 'regel', '', 'ʃ', 'sjokolade', '', 'ʃʊkʊ²lɑːdə', ''),
(512, 'kons', 's, ​ʃ', '<sj>', 'regel', '', 'ʃ', 'aksje', '', '¹ɑkːʃə', ''),
(513, 'kons', 's, ​ʃ', '<sj>', 'regel', '', 'ʃ', 'pistasj', '', 'pʰɪ¹stɑːʃ', ''),
(514, 'kons', 's, ​ʃ', '<sj>', 'regel', 'etter kort vokal i trykksterk stavelse', 'ʃː', 'dusj', '', '¹dʉʃː', ''),
(515, 'kons', 's, ​ʃ', '<sj>', 'regel', 'etter kort vokal i trykksterk stavelse', 'ʃː', 'bæsj', '', '¹bæʃː', ''),
(516, 'kons', 's, ​ʃ', '<sj>', 'regel', 'etter kort vokal i trykksterk stavelse', 'ʃː', 'dusje', '', '²dʉʃːə', ''),
(517, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skift', '', '¹ʃɪft', ''),
(518, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skinke', '', '²ʃɪŋːkʲə', ''),
(519, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skip', '', '¹ʃiːpʰ', ''),
(520, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skiver', '', '²ʃiːʋɘɾ', ''),
(521, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skynde', '', '²ʃʏn:ə', ''),
(522, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'sky', '', '¹ʃyː', ''),
(523, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skyldig', '', '²ʃʏlːdɪ', ''),
(524, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skyte', '', '²ʃy:tə', ''),
(525, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skei', '', '¹ʃæ͜ɪ', ''),
(526, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skeie', '', '²ʃæ͜ɪə', ''),
(527, 'kons', 's, ​ʃ', '<sk>', 'regel', 'foran i, y og ei', 'ʃ', 'skeiv', '', '¹ʃæ͜ɪʋ', ''),
(528, 'kons', 's, ​ʃ', '<sk>', 'spesiell uttale', 'ʃ-uttale i alle ord som har med skøyte å gjøre (men i skʲ f.eks. skøyer, Skøyen)', 'ʃ', 'skøyte', '', '²ʃœ͜ʏtə', ''),
(529, 'kons', 's, ​ʃ', '<skj>', 'regel', '', 'ʃ', 'skjev', '', '¹ʃeːʋ', ''),
(530, 'kons', 's, ​ʃ', '<skj>', 'regel', '', 'ʃ', 'skjære', '', '²ʃæːɾə', ''),
(531, 'kons', 's, ​ʃ', '<skj>', 'regel', '', 'ʃ', 'skjenke', '', '²ʃɛŋːkʲə', ''),
(532, 'kons', 's, ​ʃ', '<rs>', 'regel', 'etter lang vokal og i trykksvake stavelser', 'ʃ ', 'Lars', '', '¹lɑːʃ', ''),
(533, 'kons', 's, ​ʃ', '<rs>', 'regel', 'etter lang vokal og i trykksvake stavelser', 'ʃ ', 'Majorstua', '', 'mɑ¹juːʃʈʉɑ', ''),
(534, 'kons', 's, ​ʃ', '<rs>', 'regel', 'etter lang vokal og i trykksvake stavelser', 'ʃ ', 'forsinkelse', '', 'fɔ¹ʃɪŋːkʲəlsə', ''),
(535, 'kons', 's, ​ʃ', '<rs>', 'regel', 'etter kort vokal i trykksterke stavelser', 'ʃ ', 'mars', '', '¹mɑʃː', ''),
(536, 'kons', 's, ​ʃ', '<rs>', 'regel', 'etter kort vokal i trykksterke stavelser', 'ʃ ', 'fersken', '', '¹fæʃːkʲɘn', ''),
(537, 'kons', 's, ​ʃ', '<rs>', 'regel', 'etter kort vokal i trykksterke stavelser', 'ʃ ', 'forsvar', '', '²fɔʃːʋɑːɾ', ''),
(538, 'kons', 's, ​ʃ', '<rds>', 'regel', 'forutsetter stum d i <rd>, se der', 'ʃ', 'gårdsbruk', '', '¹goːʃpɾʉːkʲʰ', ''),
(539, 'kons', 's, ​ʃ', '<rds>', 'regel', 'følger reglene for uttale av rd (se der)', 'ʃ', 'gårdstun', '', '¹goːʃʈʰʉːn', ''),
(540, 'kons', 's, ​ʃ', '<rds>', 'regel', 'følger reglene for uttale av rd (se der)', 'ʃ', 'ordspill', '', '²uːʃpɪlː', ''),
(541, 'kons', 's, ​ʃ', '<rds>', 'regel', 'følger reglene for uttale av rd (se der)', 'ʃ', 'innabords', '', '²ɪnːɑbuːʃ', ''),
(542, 'kons', 's, ​ʃ', '<rdsj>', 'regel', '', 'ʃ', 'Nordsjøen', '', '²nuːʃøːœn', ''),
(543, 'kons', 's, ​ʃ', '<rdsk> ', 'regel', '', 'ʃ', 'bordskikk', '', '²buːʃɪkʲː', ''),
(544, 'kons', 's, ​ʃ', '<rdskj>', 'regel', '', 'ʃ', 'jordskjelv', '', '²juːʃɛlːʋ', ''),
(545, 'kons', 's, ​ʃ', '<c>', 'fremmedord', 'foran e, i, y, æ', 's', 'celle', 'latin', '²sɛlːə', ''),
(546, 'kons', 's, ​ʃ', '<c>', 'fremmedord', 'foran e, i, y, æ', 's', 'celsius', 'annet', '¹sɛlːsɪʉs', ''),
(547, 'kons', 's, ​ʃ', '<c>', 'fremmedord', 'foran e, i, y, æ', 's', 'cent', 'engelsk', '¹sɛnːtʰ', ''),
(548, 'kons', 's, ​ʃ', '<c>', 'fremmedord', '', 'ʃ', 'cello', 'italiensk', '¹ʃɛlːʊ', 'alternativ uttale med s først'),
(549, 'kons', 's, ​ʃ', '<ch>', 'fremmedord', '', 'ʃ', 'cheddar', 'engelsk', '¹ʃɛdːɑɾ', ''),
(550, 'kons', 's, ​ʃ', '<g>', 'fremmedord', 'foran g og i i noen fremmedord', 'ʃ', 'gelé', 'fransk', 'ʃɛ¹leː', ''),
(551, 'kons', 's, ​ʃ', '<g>', 'fremmedord', 'foran g og i i noen fremmedord', 'ʃ', 'generell', 'fransk', 'ʃɛnə¹ɾɛlː', ''),
(552, 'kons', 's, ​ʃ', '<g>', 'fremmedord', 'foran g og i i noen fremmedord', 'ʃ', 'gelatin', 'fransk', 'ʃɛlɑ¹tʰiːn', ''),
(553, 'kons', 's, ​ʃ', '<g>', 'fremmedord', 'foran g og i i noen fremmedord', 'ʃ', 'geni', 'fransk', 'ʃɛ¹niː', ''),
(554, 'kons', 's, ​ʃ', '<g>', 'fremmedord', 'foran g og i i noen fremmedord', 'ʃ', 'giro', 'italiensk', '¹ʃiːɾɔ', ''),
(555, 'kons', 's, ​ʃ', '<g>', 'fremmedord', 'foran g og i i noen fremmedord', 'ʃ', 'aubergine', 'fransk', 'ɔbæ¹ʃiːn', ''),
(556, 'kons', 's, ​ʃ', '<j>', 'fremmedord', '', 'ʃ', 'journal', 'fransk', 'ʃʊ¹ɳɑːɫ', ''),
(557, 'kons', 's, ​ʃ', '<j>', 'fremmedord', '', 'ʃ', 'journalist', 'fransk', 'ʃʊɳɑ¹lɪstʰ', ''),
(558, 'kons', 's, ​ʃ', '<ps->', 'fremmedord', 'i begynnelsen av ord', 's', 'psykolog', 'gresk', 'sʏkʊ¹loːgʲ', 'alternativ uttale med ps først'),
(559, 'kons', 's, ​ʃ', '<ps->', 'fremmedord', 'i begynnelsen av ord', 's', 'pseudonym', 'gresk', 'sœ͜ʏdʊ¹nyːm', 'alternativ uttale med ps først'),
(560, 'kons', 's, ​ʃ', '<sc>', 'fremmedord', 'foran e og i', 's', 'scene', 'latin', '²seːnə', ''),
(561, 'kons', 's, ​ʃ', '<sc>', 'fremmedord', 'foran e og i', 's', 'fascinere', 'latin', 'fɑsɪ¹neːɾə', ''),
(562, 'kons', 's, ​ʃ', '<sc>', 'fremmedord', '', 'ʃ', 'fascisme', 'latin', 'fɑ¹ʃɪsːmə', 's-uttale også vanlig'),
(563, 'kons', 's, ​ʃ', '<sc>', 'fremmedord', '', 'ʃ', 'crescendo', 'italiensk', 'kɾɛ¹ʃɛnːdʊ', ''),
(564, 'kons', 's, ​ʃ', '<sch>', 'fremmedord', '', 'ʃ', 'schæfer', 'tysk', '¹ʃeːfəɾ', ''),
(565, 'kons', 's, ​ʃ', '<sch>', 'fremmedord', '', 'ʃ', 'koscher', 'hebraisk', '¹kʰɔʃːɘɾ', ''),
(566, 'kons', 's, ​ʃ', '<sch>', 'fremmedord', '', 'ʃ', 'schwung', 'tysk', '¹ʃʋʊŋː', ''),
(567, 'kons', 's, ​ʃ', '<sch>', 'unntak', '', 'sk', 'Schous plass ', '', '¹skʲæ͜ʉs ¹pʰlɑsː ', 'som sk foran bakre vokaler'),
(568, 'kons', 's, ​ʃ', '<sh>', 'fremmedord', '', 'ʃ', 'sheriff', 'engelsk', '¹ʃæɾːɪf', ''),
(569, 'kons', 's, ​ʃ', '<sh>', 'fremmedord', '', 'ʃ', 'cashe', 'engelsk', '²kʰæʃːə', ''),
(570, 'kons', 's, ​ʃ', '<sh>', 'fremmedord', '', 'ʃ', 'rush', 'engelsk', '¹ɾœʃː', ''),
(571, 'kons', 's, ​ʃ', '<sh>', 'fremmedord', 'i lånord fra engelsk', 'ʃ', 'sheriff', 'engelsk', '¹ʃæɾːɪf', ''),
(572, 'kons', 's, ​ʃ', '<sh>', 'fremmedord', 'i lånord fra engelsk', 'ʃ', 'cashe', 'engelsk', '²kʰæʃːə', ''),
(573, 'kons', 's, ​ʃ', '<sh>', 'fremmedord', 'i lånord fra engelsk', 'ʃ', 'rush', 'engelsk', '¹ɾœʃː', ''),
(574, 'kons', 's, ​ʃ', '<x>', 'fremmedord', '', 's', 'xenofob', 'gresk', 'sɛnɔ¹fuːb', ''),
(575, 'kons', 's, ​ʃ', '<x>', 'fremmedord', '', 's', 'xylofon', 'gresk', 'sʏlʊ¹fuːn', ''),
(576, 'kons', 's, ​ʃ', '<z>', 'fremmedord', '', 's', 'zeppeliner', 'tysk', 'sɛpɛ¹liːnəɾ', ''),
(577, 'kons', 's, ​ʃ', '<z>', 'fremmedord', '', 's', 'quiz', 'engelsk', '¹kʲʰʋɪsː', ''),
(578, 'kons', 's, ​ʃ', '<z>', 'fremmedord', '', 's', 'nazisme', 'tysk', 'nɑ¹sɪsːmə', ''),
(579, 'kons', 'ts, tʃ, dz', '<c>', 'fremmedord', '', 'tʃ', 'cembalo', 'italiensk', '¹tʃɛmːbɑlʊ', 'også: ʃ'),
(580, 'kons', 'ts, tʃ, dz', '<cc>', 'fremmedord', '', 'tʃ', 'cappuccino', 'italiensk', 'kɑpʊ¹tʃiːnʊ', ''),
(581, 'kons', 'ts, tʃ, dz', '<ch>', 'fremmedord', '', 'tʃ', 'chat', '', '¹tʃætʰː', ''),
(582, 'kons', 'ts, tʃ, dz', '<ch>', 'fremmedord', '', 'tʃ', 'chili', '', '¹tʃɪlːɪ', ''),
(583, 'kons', 'ts, tʃ, dz', '<ch>', 'fremmedord', '', 'tʃ', 'chips', '', '¹tʃɪpːs', ''),
(584, 'kons', 'ts, tʃ, dz', '<dsj>', 'fremmedord', '', 'ʈʃ', 'budsjett', '', 'bʉʈ¹ʃɛtʰː', 'også: d som d'),
(585, 'kons', 'ts, tʃ, dz', '<dsj>', 'fremmedord', '', 'ʈʃ', 'budsjettere', '', 'bʉʈʃə¹tʰeːɾə', 'også: d som d'),
(586, 'kons', 'ts, tʃ, dz', '<g>', 'fremmedord', 'foran i og e i noen lånord fra engelsk', 'dʒ', 'gentleman ', 'engelsk', '¹dʒɛntəlmanː', ''),
(587, 'kons', 'ts, tʃ, dz', '<g>', 'fremmedord', 'foran i og e i noen lånord fra engelsk', 'dʒ', 'gin', 'engelsk', '¹dʒɪnː', ''),
(588, 'kons', 'ts, tʃ, dz', '<t>', 'fremmedord', 'foran i i noen fremmedord', 'ts', 'initiativ', 'fransk', 'ɪnɪtsɪɑ¹tʰiːʋ', ''),
(589, 'kons', 'ts, tʃ, dz', '<t>', 'fremmedord', 'foran i i noen fremmedord', 'ts', 'initial', 'latin', 'ɪnɪtsɪ¹ɑːɫ', ''),
(590, 'kons', 'ts, tʃ, dz', '<t>', 'fremmedord', 'foran i i noen fremmedord', 'ts', 'høyesterettsjustitiarius', 'latin', '²hœ͜ʏəstəɾɛtsjʉstɪtsɪɑːɾɪʉs', ''),
(591, 'kons', 'ts, tʃ, dz', '<t>', 'fremmedord', 'foran i i noen fremmedord', 'ts', 'tertial', 'latin', 'tʰæɾtsɪ¹ɑːɫ', ''),
(592, 'kons', 'ts, tʃ, dz', '<t>', 'fremmedord', 'foran i i noen fremmedord', 'ts', 'venetiansk', 'italiensk', 'ʋɛnətsɪ¹ɑːnskʲʰ', ''),
(593, 'kons', 'ts, tʃ, dz', '<zz>', 'fremmedord', '', 'tːs', 'pizza', '', '¹pʰɪtːsɑ', ''),
(594, 'kons', 'ts, tʃ, dz', '<zz>', 'unntak', '', 's', 'jazz', '', '¹jɑsː', ''),
(595, 'vok', 'i, y', '<i>', 'regel', 'kort i', 'ɪ', 'inne', '', '²ɪnːə', ''),
(596, 'vok', 'i, y', '<i>', 'regel', 'kort i', 'ɪ', 'rips', '', '¹ɾɪpːs', ''),
(597, 'vok', 'i, y', '<i>', 'regel', 'kort i', 'ɪ', 'gummi', '', '¹gʲʉmːɪ', ''),
(598, 'vok', 'i, y', '<i>', 'regel', 'lang i', 'iː', 'is', '', '¹iːs', ''),
(599, 'vok', 'i, y', '<i>', 'regel', 'lang i', 'iː', 'april', '', 'ɑ¹pʰɾiːl', ''),
(600, 'vok', 'i, y', '<i>', 'regel', 'lang i', 'iː', 'aristokrati', '', 'ɑɾɪstʊkʲɾɑ¹tʰiː', ''),
(601, 'vok', 'i, y', '<y>', 'regel', 'kort y', 'ʏ', 'lykt', '', '¹lʏkʲ:t', ''),
(602, 'vok', 'i, y', '<y>', 'regel', 'lang y', 'yː', 'fyr', '', '¹fy:ɾ', ''),
(603, 'vok', 'i, y', '<y>', 'fremmedord', 'i noen lånord', 'ɪ', 'sexy', 'engelsk', '¹sɛkʲːsɪ', ''),
(604, 'vok', 'i, y', '<y>', 'fremmedord', 'i noen lånord', 'ɪ', 'bandy', 'engelsk', '¹bænːdɪ', ''),
(605, 'vok', 'i, y', '<y>', 'fremmedord', 'i noen lånord fra engelsk', 'ɑ͜ɪ', 'cyber', 'engelsk', '¹sɑ͜ɪbɘɾ', ''),
(606, 'vok', 'i, y', '<y>', 'fremmedord', 'i noen lånord fra engelsk', 'ɑ͜ɪ', 'byte', 'engelsk', '¹bɑ͜ɪtʰ', ''),
(607, 'vok', 'i, y', '<y>', 'fremmedord', 'i noen lånord', 'j / jː', 'yoga', 'sanskrit', '¹joːgɑ', ''),
(608, 'vok', 'i, y', '<y>', 'fremmedord', 'i noen lånord', 'j / jː', 'soya', 'japansk', '¹sɔjːɑ', ''),
(609, 'vok', 'i, y', '<e>', 'spesiell uttale', '', 'iː', 'de                ', '', '¹diː', ''),
(610, 'vok', 'i, y', '<ea> ', 'fremmedord', 'i lånord fra engelsk', 'iː', 'jeans', 'engelsk', '¹ji:ns / ¹dʒi:ns', ''),
(611, 'vok', 'i, y', '<ea> ', 'fremmedord', 'i lånord fra engelsk', 'iː', 'beat ', 'engelsk', '¹biːtʰ', ''),
(612, 'vok', 'i, y', '<ea> ', 'fremmedord', 'i lånord fra engelsk', 'iː', 'healer', 'engelsk', '¹hiːlɘɾ', ''),
(613, 'vok', 'i, y', '<ee>', 'fremmedord', 'i lånord fra engelsk', 'iː', 'feedback', 'engelsk', '¹fiːdbækʲʰː', ''),
(614, 'vok', 'i, y', '<ee>', 'fremmedord', 'i lånord fra engelsk', 'iː', 'keeper ', 'engelsk', '¹kʲiːpɘɾ', ''),
(615, 'vok', 'i, y', '<ey>', 'fremmedord', 'i lånord fra engelsk', 'ɪ', 'hockey', 'engelsk', '¹hɔkʲːɪ', ''),
(616, 'vok', 'i, y', '<ey>', 'fremmedord', 'i lånord fra engelsk', 'ɪ', 'trolleybuss', 'engelsk', '¹tʰɾɔɫːɪbʉsː', ''),
(617, 'vok', 'i, y', '<ey>', 'fremmedord', 'i lånord fra engelsk', 'ɪ', 'volleyball', 'engelsk', '¹ʋɔɫːɪbɑɫː', ''),
(618, 'vok', 'i, y', '<ey>', 'fremmedord', 'i lånord fra engelsk', 'iː', 'keyboard', 'engelsk', '¹kʲiːboːɖ', ''),
(619, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'kort, trykksterk vokal', 'ɛ', 'elske', '', '²ɛlːskʲə', ''),
(620, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'lang, trykksterk vokal', 'eː', 'krem', '', '¹kʲɾeːm', ''),
(621, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser og suffikser', 'ə', 'hvete', '', '²ʋeːtə', ''),
(622, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser og suffikser', 'ə', 'rutete', '', '²ɾʉːtətə', ''),
(623, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser og suffikser', 'ə', 'høyere', '', '²hœ͜ʏəɾə', ''),
(624, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser og suffikser', 'ə', 'jaget', '', '²jɑːgʲətʰ', ''),
(625, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser foran r og l', 'ə', 'husker', '', '²hʉsːkʲɘɾ', ''),
(626, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser foran r og l', 'ə', 'åkrer', '', '¹oːkʲɾɘɾ', ''),
(627, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser foran r og l', 'ə', 'vakker', '', '¹ʋɑkːɘɾ', ''),
(628, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser foran r og l', 'ə', 'hybel', '', '¹hyːbɘl', ''),
(629, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'i endelser foran r og l', 'ə', 'høvel', '', '¹hœʋːɘl', ''),
(630, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'endelsen -er', 'ə', 'holder ', '', '¹hɔɫːɘɾ', ''),
(631, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rt>, <rs>)', 'æ', 'persille', '', 'pæ¹ʃɪlːə', ''),
(632, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rt>, <rs>)', 'æ', 'verden', '', '¹ʋæɾːdn', ''),
(633, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rt>, <rs>)', 'æ', 'verpe', '', '²ʋæɾːpə', ''),
(634, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rd>)', 'æː', 'er', '', '¹æːɾ', ''),
(635, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rd>)', 'æː', 'her', '', '¹hæːɾ', ''),
(636, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rd>)', 'æː', 'perle', '', '²pæːlə', ''),
(637, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rd>)', 'æː', 'jern', '', '¹jæːɳ', ''),
(638, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> (inkl. <rl>, <rn>, <rd>)', 'æː', 'ferdig', '', '²fæːɖɪ', ''),
(639, 'vok', 'e, ø, æ, a', '<e>', 'unntak', '', 'eː', 'flere', '', '¹fleːɾə', ''),
(640, 'vok', 'e, ø, æ, a', '<e>', 'unntak', '', 'eː', 'mer', '', '¹meːɾ', ''),
(641, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'suffikset -ere bøyde former:, -erer, -erte, -ert', 'eː', ' -ere', '', ' -¹eːɾə, -¹eːɾɘɾ, -¹eːʈə, -¹eːʈ', ''),
(642, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> i enstavelsesverb', 'eː', 'ler ', '', '¹leːɾ', ''),
(643, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> i enstavelsesverb', 'eː', 'ser', '', '¹seːɾ', ''),
(644, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'foran <r> i enstavelsesverb', 'eː', 'rer', '', '¹ɾeːɾ', ''),
(645, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t og d stum i endelsene -el/-else', '-', 'handel', '', '¹hɑnːdl̩', ''),
(646, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t og d stum i endelsene -el/-else', '-', 'middel', '', '¹mɪdːl̩', ''),
(647, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t og d stum i endelsene -el/-else', '-', 'nytelse', '', '²nyːtl̩sə', ''),
(648, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t og d stum i endelsene -el/-else', '-', 'utsettelse', '', '¹ʉːtsɛtːl̩sə', ''),
(649, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'dyden', '', '¹dyːdnͅ', ''),
(650, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'ballen', '', '¹bɑɫːnͅ', ''),
(651, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'mannen', '', '¹mɑnːnͅ', ''),
(652, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'posen', '', '²pʰuːsnͅ', ''),
(653, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'gutten', '', '¹gʲʉːtnͅ', ''),
(654, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'badene', '', '¹bɑːdn̩ə', ''),
(655, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'fuglene', '', '²fʉːln͏ͅə', ''),
(656, 'vok', 'e, ø, æ, a', '<e>', 'regel', 'etter t, d, n og s stum i endelsene -en/-ene', '-', 'guttene', '', '²gʲʉtːn͏ͅə', ''),
(657, 'vok', 'e, ø, æ, a', '<e>', 'fremmedord', 'i noen lånord fra fransk og engelsk', '-', 'race', 'engelsk', '¹ɾeːs', ''),
(658, 'vok', 'e, ø, æ, a', '<e>', 'fremmedord', 'i noen lånord fra fransk og engelsk', '-', 'ampere ', 'fransk', 'ɑm¹pʰæ:ɾ', ''),
(659, 'vok', 'e, ø, æ, a', '<e>', 'fremmedord', 'foran n i noen lånord fra fransk ', 'ɑ', 'entre', 'fransk', 'ɑŋ¹tʰɾeː', ''),
(660, 'vok', 'e, ø, æ, a', '<e>', 'fremmedord', 'foran n i noen lånord fra fransk ', 'ɑ', 'prevensjon', 'fransk', 'pʰɾəʋɑŋ¹ʃuːn', ''),
(661, 'vok', 'e, ø, æ, a', '<e>', 'fremmedord', 'foran nt i noen lånord fra fransk', 'ɑ', 'departement', '', 'dɛpɑʈə¹mɑŋː', ''),
(662, 'vok', 'e, ø, æ, a', '<e>', 'fremmedord', 'foran nt i noen lånord fra fransk', 'ɑ', 'arrangement ', '', 'ɑɾɑŋʃə¹mɑŋː', ''),
(663, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'når det ikke følger <r> etter <æ>', 'e', 'væske', '', '²ʋɛsːkʲə', ''),
(664, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'når det ikke følger <r> etter <æ>', 'e', 'ætt', '', '¹ɛtː', ''),
(665, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'når det ikke følger <r> etter <æ> (merk grunnord med å: så, våt, våpen)', 'eː', 'sæd', '', '¹seːd', ''),
(666, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'når det ikke følger <r> etter <æ> (merk grunnord med å: så, våt, våpen)', 'eː', 'væte', '', '²ʋeːtə', ''),
(667, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'når det ikke følger <r> etter <æ> (merk grunnord med å: så, våt, våpen)', 'eː', 'væpne', '', '²ʋeːpnə', ''),
(668, 'vok', 'e, ø, æ, a', '<æ>', 'unntak', '', 'æ', 'æsj', '', '¹æʃː', ''),
(669, 'vok', 'e, ø, æ, a', '<æ>', 'unntak', '', 'æ', 'bæsj', '', '¹bæʃː', ''),
(670, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'foran <r> ', 'æ', 'lærd', '', '¹læɾːd', ''),
(671, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'foran <r>, <l> og i utlyd', 'æː', 'bære', '', '²bæːɾə', ''),
(672, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'foran <r>, <l> og i utlyd', 'æː', 'fæl', '', '¹fæːl', ''),
(673, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'foran <r>, <l> og i utlyd', 'æː', 'tæl', '', '¹tʰæːl', ''),
(674, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'foran <r>, <l> og i utlyd', 'æː', 'hæ', '', '¹hæː', ''),
(675, 'vok', 'e, ø, æ, a', '<æ>', 'regel', 'foran <r>, <l> og i utlyd', 'æː', 'bæ', '', '¹bæː', ''),
(676, 'vok', 'e, ø, æ, a', '<ø>', 'regel', 'kort ø', 'œ', 'østers', '', '¹œsːtəʃ', ''),
(677, 'vok', 'e, ø, æ, a', '<ø>', 'regel', 'kort ø', 'œ', 'mørk', '', '¹mœɾːkʲʰ', ''),
(678, 'vok', 'e, ø, æ, a', '<ø>', 'regel', 'lang ø', 'øː', 'løve', '', '²løːʋə', ''),
(679, 'vok', 'e, ø, æ, a', '<ø>', 'regel', 'lang ø', 'øː', 'øre', '', '²øːɾə', ''),
(680, 'vok', 'e, ø, æ, a', '<ø>', 'regel', 'lang ø', 'øː', 'miljø', '', 'mɪl¹jøː', ''),
(681, 'vok', 'e, ø, æ, a', '<a>', 'regel', 'kort a', 'ɑ', 'lampe', '', '²lɑmːpə', ''),
(682, 'vok', 'e, ø, æ, a', '<a>', 'regel', 'lang a', 'ɑː', 'dato', '', '¹dɑːtʊ', ''),
(683, 'vok', 'e, ø, æ, a', '<a>', 'fremmedord', 'i lånord fra engelsk', 'æ', 'dragshow', 'engelsk', '¹dɾægʲːʃɔ͜͜ʊ', ''),
(684, 'vok', 'e, ø, æ, a', '<a>', 'fremmedord', 'i lånord fra engelsk', 'æ', 'band (musikk-)', 'engelsk', '¹bænː', ''),
(685, 'vok', 'e, ø, æ, a', '<a>', 'fremmedord', 'i lånord fra engelsk', 'æ', 'tanks', 'engelsk', '¹tʰæŋːkʲs', ''),
(686, 'vok', 'e, ø, æ, a', '<a>', 'fremmedord', 'i lånord fra engelsk', 'æ', 'yankee ', 'engelsk', '¹jæŋːki', ''),
(687, 'vok', 'e, ø, æ, a', '<ea> ', 'fremmedord', 'i lånord fra engelsk', 'ɛ', 'heading', 'engelsk', '¹hɛdːɪŋ', ''),
(688, 'vok', 'e, ø, æ, a', '<ea> ', 'fremmedord', 'i lånord fra engelsk', 'ɛ', 'heade', 'engelsk', '²hɛːdə', ''),
(689, 'vok', 'e, ø, æ, a', '<u>', 'fremmedord', 'i lånord fra engelsk', 'œ', 'dubbe', 'engelsk', '²dœbːə', ''),
(690, 'vok', 'e, ø, æ, a', '<u>', 'fremmedord', 'i lånord fra engelsk', 'œ', 'pub', 'engelsk', '¹pʰœbː', ''),
(691, 'vok', 'e, ø, æ, a', '<u>', 'fremmedord', 'i lånord fra engelsk', 'œ', 'flush', 'engelsk', ' ¹flœʃː', ''),
(692, 'vok', 'e, ø, æ, a', '<u>', 'fremmedord', 'i lånord fra engelsk', 'œ', 'rush', 'engelsk', '¹ɾœʃː', ''),
(693, 'vok', 'e, ø, æ, a', '<y>', 'spesiell uttale', '', 'œ', 'sytten           ', '', '²sœtːn̩', ''),
(694, 'vok', 'e, ø, æ, a', '<y>', 'spesiell uttale', '', 'œ', 'sytti              ', '', '¹sœtːɪ', ''),
(695, 'vok', 'u, o, å', '<u>', 'regel', '', 'ʉ', 'bunn', '', '¹bʉnː', ''),
(696, 'vok', 'u, o, å', '<u>', 'regel', '', 'ʉ', 'ruste', '', '²ɾʉsːtə', ''),
(697, 'vok', 'u, o, å', '<u>', 'regel', '', 'ʉ', 'Burundi', '', 'bʉ¹ɾʉnːdɪ', ''),
(698, 'vok', 'u, o, å', '<u>', 'regel', 'foran <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'sukker', '', '¹sʊkʲːɘɾ', ''),
(699, 'vok', 'u, o, å', '<u>', 'regel', 'foran <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'nummer', '', '¹nʊmːɘɾ', ''),
(700, 'vok', 'u, o, å', '<u>', 'regel', 'foran <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'tung', '', '¹tʰʊŋː', ''),
(701, 'vok', 'u, o, å', '<u>', 'regel', 'foran <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'Ungarn', '', '¹ʊŋːɡɑɳ', ''),
(702, 'vok', 'u, o, å', '<u>', 'regel', 'foran <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'munk', '', '¹mʊŋːkʲʰ', ''),
(703, 'vok', 'u, o, å', '<u>', 'regel', 'foran <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'bukser', '', '²bʊkʲːsɘɾ', ''),
(704, 'vok', 'u, o, å', '<u>', 'regel', 'foran <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'jukse', '', ' ²jʊkʲːsə', ''),
(705, 'vok', 'u, o, å', '<u>', 'unntak', '[ʊ] foran andre konsonanter enn <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'truffet ', '', '²tʰɾʊfːɘtʰ', 'verb part.'),
(706, 'vok', 'u, o, å', '<u>', 'unntak', '[ʊ] foran andre konsonanter enn <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'hjulpet ', '', '²jʊlːpətʰ', 'verb part.'),
(707, 'vok', 'u, o, å', '<u>', 'unntak', '[ʊ] foran andre konsonanter enn <kk>, <m>, <ng>, <nk>, <k+konsonant>', 'ʊ', 'skuff ', '', '¹skʲʊfː', 'subst., men part./adj. har [ʉ]: ²skʲʉfːɘtʰ'),
(708, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <k>', 'ʉ', 'frukt ', '', '¹fɾʉkʲːtʰ', ''),
(709, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <k>', 'ʉ', 'dukke', '', '²dʉkʲːə', ''),
(710, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <k>', 'ʉ', 'tukle ', '', '²tʰʉkʲːlə', ''),
(711, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <m>', 'ʉ', 'sum  ', '', '¹sʉmː', ''),
(712, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <m>', 'ʉ', 'slum ', '', '¹ʃlʉmː', ''),
(713, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <m>', 'ʉ', 'gummi', '', '¹gʲʉmːɪ', ''),
(714, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <m>', 'ʉ', 'stum', '', '¹stʉmː', ''),
(715, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <m>', 'ʉ', 'triumf', '', 'tʰɾɪ¹ʉmːf', ''),
(716, 'vok', 'u, o, å', '<u>', 'unntak', '[ʉ] selv om <u> står foran <m>', 'ʉ', 'skummel', '', '¹skʲʉmːɘl', ''),
(717, 'vok', 'u, o, å', '<u>', 'regel', '', 'ʉː', 'brun', '', '¹bɾʉːn', ''),
(718, 'vok', 'u, o, å', '<u>', 'regel', '', 'ʉː', 'luke', '', '²lʉːkʲə', ''),
(719, 'vok', 'u, o, å', '<u>', 'regel', '', 'ʉː', 'Kamerun', '', 'kʰɑmə¹ɾʉːn', ''),
(720, 'vok', 'u, o, å', '<u>', 'regel', '', 'ʉː', 'skru', '', '¹skʲɾʉː', ''),
(721, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'som', '', '¹sɔmː', ''),
(722, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'orkidé', '', 'ɔɾkʲɪ¹deː', ''),
(723, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'balkong', '', 'bɑɫ¹kʰɔŋː', ''),
(724, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'bolle', '', '²bɔɫːə', ''),
(725, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'kommer', '', '¹kʰɔmːɘɾ', ''),
(726, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'Norge', '', '²nɔɾːgʲə', ''),
(727, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'forandre ', '', 'fɔɾ¹ɑnːdɾə ', ''),
(728, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'forretning', '', 'fɔ¹ɾɛtːnɪŋ', ''),
(729, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'lønnsom ', '', '²lœnːsɔm', ''),
(730, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er kort', 'ɔ', 'tvilsom ', '', '¹tʰʋiːlsɔm', ''),
(731, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'bonde', '', '²bʊnːə', ''),
(732, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'borte', '', '²bʊʈːə', ''),
(733, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'ekorn', '', '²ɛkʲːʊɳ', ''),
(734, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'hoste', '', '²hʊsːtə', ''),
(735, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'dato', '', '¹dɑːtʊ', ''),
(736, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'nikotin', '', 'nɪkʲʊ¹tʰiːn', ''),
(737, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'aristokrati', '', 'ɑɾɪstʊkʲɾɑ¹tʰiː', ''),
(738, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <nd>, <rt>, <rn>, <st>, og i slutten av ord', 'ʊ', 'kimono', '', '¹kʲʰɪmːʊnʊ', ''),
(739, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er lang', 'uː', 'noen', '', '²nuːʊn', ''),
(740, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er lang', 'uː', 'mot', '', '¹muːt', ''),
(741, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er lang', 'uː', 'fjord', '', '¹fjuːɾ', ''),
(742, 'vok', 'u, o, å', '<o>', 'regel', 'Hovedregel når vokalen er lang', 'uː', 'rosa', '', '¹ɾuːsɑ', ''),
(743, 'vok', 'u, o, å', '<o>', 'unntak', 'Prefikset fore- uttales med [oː] selv om vokalen er lang', 'uː', 'forebygge ', '', '²foːɾəbʏɡʲːə', ''),
(744, 'vok', 'u, o, å', '<o>', 'unntak', 'Prefikset fore- uttales med [oː] selv om vokalen er lang', 'uː', 'foregå ', '', '²foːɾəɡoː', ''),
(745, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <v> og <g>', 'oː', 'tog', '', '¹tʰoːgʲ', ''),
(746, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <v> og <g>', 'oː', 'psykolog', '', 'sʏkʊ¹loːgʲ', ''),
(747, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <v> og <g>', 'oː', 'over', '', '¹oːʋɘɾ', ''),
(748, 'vok', 'u, o, å', '<o>', 'regel', 'vanligvis foran <v> og <g>', 'oː', 'love', '', '²loːʋə', ''),
(749, 'vok', 'u, o, å', '<o>', 'unntak', '[u:] selv om <o> står foran <v> eller <g>', 'uː', 'hoved-', '', '²huːʋəd-', ''),
(750, 'vok', 'u, o, å', '<o>', 'unntak', '[u:] selv om <o> står foran <v> eller <g>', 'uː', 'skog ', '', '¹skuːgʲ', ''),
(751, 'vok', 'u, o, å', '<o>', 'unntak', '[u:] selv om <o> står foran <v> eller <g>', 'uː', 'pedagog .', '', 'pʰɛdɑ¹guːgʲ', ''),
(752, 'vok', 'u, o, å', '<o>', 'unntak', '[u:] selv om <o> står foran <v> eller <g>', 'uː', 'synagoge', '', 'sʏnɑ²guːgʲə', ''),
(753, 'vok', 'u, o, å', '<å>', 'regel', 'kort å', 'ɔ', 'gått', '', '¹gɔtː', ''),
(754, 'vok', 'u, o, å', '<å>', 'regel', 'kort å', 'ɔ', 'åtti', '', '¹ɔtːɪ', ''),
(755, 'vok', 'u, o, å', '<å>', 'regel', 'lang å', 'oː', 'nål', '', '¹noːɫ', ''),
(756, 'vok', 'u, o, å', '<å>', 'regel', 'lang å', 'oː', 'åre', '', '²oːɾə', ''),
(757, 'vok', 'u, o, å', '<au>', 'fremmedord', 'i noen franske lånord', 'ɔ', 'aubergine', 'fransk', 'ɔbæ¹ʃiːn', ''),
(758, 'vok', 'u, o, å', '<au>', 'fremmedord', 'i noen franske lånord', 'ɔ', 'café-au-lait', 'fransk', 'kɑ¹feːɔ¹leː', ''),
(759, 'vok', 'u, o, å', '<au>', 'fremmedord', 'i noen franske lånord', 'oː ', 'bordeauxvin', 'fransk', 'bɔ¹ɖoːʋiːn', ''),
(760, 'vok', 'u, o, å', '<au>', 'fremmedord', 'i noen franske lånord', 'oː ', 'comme il feaux', 'fransk', 'kʰɔmɪl¹foː', ''),
(761, 'vok', 'u, o, å', '<au>', 'fremmedord', '', 'ʉ', 'restaurant ', 'fransk', 'ɾɛstʉ¹ɾɑŋː', ''),
(762, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk', 'ʉ', 'gourmand', 'fransk', 'gʲʉɾ¹mɑŋː', ''),
(763, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk', 'ʉ', 'gourmet', 'fransk', 'gʲʉɾ¹meː', ''),
(764, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk og andre spåk', 'ʊ', 'journal', 'fransk', 'ʃʊ¹ɳɑːɫ', ''),
(765, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk og andre spåk', 'ʊ', 'journalist', 'fransk', 'ʃʊɳɑ¹lɪstʰ', ''),
(766, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk og andre spåk', 'ʊ', 'couscous', 'fransk', '¹kʰʊsːkʰʊs', ''),
(767, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk og andre spåk', 'ʊ', 'croupier', 'fransk', 'kʲɾʊ¹pjeː', ''),
(768, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk og andre spåk', 'uː', 'glamour', 'engelsk', 'gʲlɑ¹muːɾ', ''),
(769, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk og andre spåk', 'uː', 'ouzo', 'nygresk', '¹uːsʊ', ''),
(770, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk', 'uː', 'à jour', 'fransk', 'ɑ¹ʃuːɾ', ''),
(771, 'vok', 'u, o, å', '<ou>', 'fremmedord', 'i noen lånord fra fransk', 'uː', 'rouge', 'fransk', '¹ɾʉːʃ', ''),
(772, 'vok', 'u, o, å', '<ui>', 'fremmedord', 'i noen lånord fra engelsk', 'uː', 'cruiseskip', 'engelsk', '¹kʲɾʉːsʃiːpʰ', ''),
(773, 'vok', 'ei, øy, ai', '<ei>', 'regel', '', 'æ͜ɪ', 'stein', '', '¹stæ͜ɪn', ''),
(774, 'vok', 'ei, øy, ai', '<ei>', 'fremmedord', 'i noen lånord', 'ɛ¹iː', 'protein', 'gresk', 'pɾʊtɛ¹iːn', ''),
(775, 'vok', 'ei, øy, ai', '<eg>', 'spesiell uttale', '', 'æ͜ɪ', 'jeg               ', '', '¹jæ͜ɪ', ''),
(776, 'vok', 'ei, øy, ai', '<eg>', 'spesiell uttale', '', 'æ͜ɪ', 'meg             ', '', '¹mæ͜ɪ', ''),
(777, 'vok', 'ei, øy, ai', '<eg>', 'spesiell uttale', '', 'æ͜ɪ', 'deg              ', '', '¹dæ͜ɪ', ''),
(778, 'vok', 'ei, øy, ai', '<eg>', 'spesiell uttale', '', 'æ͜ɪ', 'seg               ', '', '¹sæ͜ɪ', ''),
(779, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før l (men uttales som gl i megler, egle, regle m.fl.)', 'æ͜ɪ', 'negl', '', '¹næ͜ɪl', ''),
(780, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før l (men uttales som gl i megler, egle, regle m.fl.)', 'æ͜ɪ', 'segl', '', '¹sæ͜ɪl', ''),
(781, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før l (men uttales som gl i megler, egle, regle m.fl.)', 'æ͜ɪ', 'kjegle', '', '²çæ͜ɪlə', ''),
(782, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før l (men uttales som gl i megler, egle, regle m.fl.)', 'æ͜ɪ', 'snegl', '', '¹snæ͜ɪl', ''),
(783, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før l (men uttales som gl i megler, egle, regle m.fl.)', 'æ͜ɪ', 'tegl', '', '¹tʰæ͜ɪl', ''),
(784, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før n', 'æ͜ɪ', 'regne', '', '²ɾæ͜ɪnə', ''),
(785, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før n', 'æ͜ɪ', 'velegnet', '', '²ʋɛlːæ͜ɪnətʰ', ''),
(786, 'vok', 'ei, øy, ai', '<eg>', 'regel', 'eg før n', 'æ͜ɪ', 'tilegne', '', '¹tʰɪlːæ͜ɪnə', ''),
(787, 'vok', 'ei, øy, ai', '<eg>', 'unntak', 'eg før n ikke som æi', 'æ͜ɪ', 'egne ', '', '²eːgʲnə', ''),
(788, 'vok', 'ei, øy, ai', '<ek>', 'spesiell uttale', '', 'æ͜ɪ', 'seksten        ', '', '²sæ͜ɪstn̩', ''),
(789, 'vok', 'ei, øy, ai', '<øy>', 'regel', '', 'œ͜ʏ', 'fløyte', '', '²flœ͜ʏtə', ''),
(790, 'vok', 'ei, øy, ai', '<øg>', 'regel', 'øg før n', 'œ͜ʏ', 'døgn', '', '¹dœ͜ʏn', ''),
(791, 'vok', 'ei, øy, ai', '<øg>', 'regel', 'øg før n', 'œ͜ʏ', 'løgn', '', '¹lœ͜ʏn', ''),
(792, 'vok', 'ei, øy, ai', '<eu>', 'regel', '', 'œ͜ʏ', 'pseudonym', 'gresk', 'sœ͜ʏdʊ¹nyːm', ''),
(793, 'vok', 'ei, øy, ai', '<eu>', 'regel', '', 'œ͜ʏ', 'freudiansk', '', 'fɾœ͜ʏdɪ¹ɑːnskʲʰː', ''),
(794, 'vok', 'ei, øy, ai', '<ai>', 'regel', '', 'ɑ͜ɪ', 'mai', '', '¹mɑ͜ɪ', ''),
(795, 'vok', 'ei, øy, ai', '<ai>', 'regel', '', 'ɑ͜ɪ', 'hai', '', '¹hɑ͜ɪ', ''),
(796, 'vok', 'ei, øy, ai', '<ai>', 'regel', '', 'ɑ͜ɪ', 'mais', '', '¹mɑ͜ɪs', ''),
(797, 'vok', 'ei, øy, ai', '<ai>', 'regel', '', 'ɑ͜ɪ', 'pai', '', '¹pʰɑ͜ɪ', ''),
(798, 'vok', 'ei, øy, ai', '<ai>', 'fremmedord', 'i noen lånord', 'ɑ¹iː', 'naiv', 'fransk', 'nɑ¹iːʋ', ''),
(799, 'vok', 'ei, øy, ai', '<ai>', 'fremmedord', 'i noen lånord', 'ɑ¹iː', 'kokain', 'spansk', 'kʰʊkɑ¹iːn', ''),
(800, 'vok', 'ei, øy, ai', '<ai>', 'fremmedord', 'i noen lånord fra engelsk', 'ɛ͜ɪ', 'maile', 'engelsk', '²mɛ͜ɪlə', ''),
(801, 'vok', 'ei, øy, ai', '<ai>', 'fremmedord', 'i noen lånord fra engelsk', 'ɛ͜ɪ', 'aids', 'engelsk', '¹ɛ͜ɪts', ''),
(802, 'vok', 'ei, øy, ai', '<ai>', 'fremmedord', 'i noen lånord fra engelsk', 'ɛ͜ɪ', 'cocktail', 'engelsk', '¹kʰɔkʲːtʰɛ͜ɪl', ''),
(803, 'vok', 'ei, øy, ai', '<ay>', 'fremmedord', '', 'ɑ͜ɪ', 'maya', '', '¹mɑ͜ɪɑ', ''),
(804, 'vok', 'ei, øy, ai', '<ay>', 'fremmedord', '', 'ɑ͜ɪ', 'papaya', '', 'pʰɑ¹pʰɑ͜ɪɑ', ''),
(805, 'vok', 'ei, øy, ai', '<ay>', 'fremmedord', '', 'ɛ͜ɪ', 'layout', '', '¹lɛ͜ɪɑ͜ʊtʰ', ''),
(806, 'vok', 'ei, øy, ai', '<ay>', 'fremmedord', '', 'ɛ͜ɪ', 'essay', '', '¹ɛsːɛ͜ɪ', ''),
(807, 'vok', 'ei, øy, ai', '<ey>', 'fremmedord', '', 'ɑ͜ɪ', 'eyeliner', '', '¹ɑ͜ɪlɑ͜ɪnɘɾ', ''),
(808, 'vok', 'ei, øy, ai', '<ey>', 'fremmedord', '', 'ɛ͜ɪ', 'geysir', 'islandsk', '¹ɡʲɛ͜ɪsɪɾ', ''),
(809, 'vok', 'ei, øy, ai', '<ey>', 'fremmedord', '', 'ɛ͜ɪ', 'surveyundersøkelse', 'engelsk', '¹søːɾʋɛ͜ɪʉnəʃøːkʲɘlsə', ''),
(810, 'vok', 'au, ou, oi, ui', '<au>', 'regel', '', 'æ͜ʉ', 'august', '', 'æ͜ʉ¹gʲʉsːtʰ', ''),
(811, 'vok', 'au, ou, oi, ui', '<au>', 'regel', '', 'æ͜ʉ', 'maur', '', '¹mæ͜ʉɾ', ''),
(812, 'vok', 'au, ou, oi, ui', '<au>', 'regel', '', 'æ͜ʉ', 'sau', '', '¹sæ͜ʉ', ''),
(813, 'vok', 'au, ou, oi, ui', '<eu>', 'regel', '', 'æ͜ʉ', 'europeisk', '', 'æ͜ʉɾʊ¹pʰeːɪskʲ', ''),
(814, 'vok', 'au, ou, oi, ui', '<eu>', 'regel', '', 'æ͜ʉ', 'euro', '', '¹æ͜ʉɾʊ', ''),
(815, 'vok', 'au, ou, oi, ui', '<eu>', 'regel', '', 'æ͜ʉ', 'terapeut', 'gresk', 'tʰæɾɑ¹pʰæ͜ʉtʰ', ''),
(816, 'vok', 'au, ou, oi, ui', '<oi>', 'fremmedord', 'når i samme stavelse', 'ɔ͜ʏ', 'boikott', 'engelsk', '¹bɔ͜ʏkʰɔtː', ''),
(817, 'vok', 'au, ou, oi, ui', '<oi>', 'fremmedord', 'når i samme stavelse', 'ɔ͜ʏ', 'broiler', 'engelsk', '¹bɾɔ͜ʏlɘɾ', ''),
(818, 'vok', 'au, ou, oi, ui', '<ou>', 'fremmedord', 'i noen lånord fra engelsk', 'ɑ͜ʊ', 'blackout', 'engelsk', '¹blækʲːɑ͜ʊtʰ', ''),
(819, 'vok', 'au, ou, oi, ui', '<ou>', 'fremmedord', 'i noen lånord fra engelsk', 'ɑ͜ʊ', 'blowout', 'engelsk', '¹blɔ͜ʊɑ͜ʊtʰ', ''),
(820, 'vok', 'au, ou, oi, ui', '<ou>', 'fremmedord', 'i noen lånord fra engelsk', 'ɑ͜ʊ', 'layout', 'engelsk', '¹lɛ͜ɪɑ͜ʊtʰ', ''),
(821, 'vok', 'au, ou, oi, ui', '<ou>', 'fremmedord', 'i noen lånord fra engelsk', 'ɔ͜ʊ', 'soul', 'engelsk', '¹sɔ͜ʊl', ''),
(822, 'vok', 'au, ou, oi, ui', '<ow>', 'fremmedord', '', 'ɑ͜ʊ', 'Downs syndrom', 'engelsk', '¹dɑ͜ʊnsʏn¹dɾuːm', ''),
(823, 'vok', 'au, ou, oi, ui', '<ow>', 'fremmedord', '', 'ɑ͜ʊ', 'knowhow', 'engelsk', '¹nɔ͜ʊhɑ͜ʊ', ''),
(824, 'vok', 'au, ou, oi, ui', '<ow>', 'fremmedord', '', 'ɔ͜ʊ', 'bowling', 'engelsk', '¹bɔ͜ʊlɪŋ', ''),
(825, 'vok', 'au, ou, oi, ui', '<ow>', 'fremmedord', '', 'ɔ͜ʊ', 'blowout', 'engelsk', '¹blɔ͜ʊɑ͜ʊtʰ', ''),
(826, 'vok', 'au, ou, oi, ui', '<ow>', 'fremmedord', '', 'ɔ͜ʊ', 'knowhow', 'engelsk', '¹nɔ͜ʊhɑ͜ʊ', ''),
(827, 'vok', 'au, ou, oi, ui', '<ow>', 'fremmedord', '', 'ɔ͜ʊ', 'show ', 'engelsk', '¹ʃɔ͜ʊ', ''),
(828, 'vok', 'au, ou, oi, ui', '<ui>', 'regel', '', 'ʉ͜ɪ', 'hui!', '', '¹hʉ͜ɪ', '');
";

// Run SQL and log result
plugin_log($wpdb->query($sql));
plugin_log($wpdb->print_error($sql));

}



/**
 * Write an entry to a log file in the uploads directory.
 *
 * @since x.x.x
 *
 * @param mixed $entry String or array of the information to write to the log.
 * @param string $file Optional. The file basename for the .log file.
 * @param string $mode Optional. The type of write. See 'mode' at https://www.php.net/manual/en/function.fopen.php.
 * @return boolean|int Number of bytes written to the lof file, false otherwise.
 */
if ( ! function_exists( 'uttale_plugin_log' ) ) {
	function plugin_log( $entry, $mode = 'a', $file = 'plugin' ) {
		// Get WordPress uploads directory.
		$upload_dir = wp_upload_dir();
		$upload_dir = $upload_dir['basedir'];
		// If the entry is array, json_encode.
		if ( is_array( $entry ) ) {
			$entry = json_encode( $entry );
		}
		// Write the log file.
		$file  = $upload_dir . '/' . $file . '.log';
		$file  = fopen( $file, $mode );
		$bytes = fwrite( $file, current_time( 'mysql' ) . "::" . $entry . "\n" );
		fclose( $file );
		return $bytes;
	}
}
